export const RARITY_LABELS = {
  common: '普通',
  rare: '稀有',
  elite: '精英',
  epic: '史诗',
  legendary: '传奇',
}

export const RARITY_VARIANCE = {
  common: 0.1,
  rare: 0.15,
  elite: 0.2,
  epic: 0.25,
  legendary: 0.3,
}

export const DEPT_META = {
  R: { label: '研发部', short: '研发', color: 'rd', icon: 'R' },
  S: { label: '销售部', short: '销售', color: 'sales', icon: 'S' },
  O: { label: '运营部', short: '运营', color: 'ops', icon: 'O' },
  NONE: { label: '通用', short: '通用', color: 'neutral', icon: '*' },
}

/** @deprecated Use STAGES instead */
export const LEVELS = [
  { id: 1, milestone: 'A 轮融资', theme: '起步打 PMF', target: 1200, startCash: 45, startBudget: 60, maintenance: 8 },
  { id: 2, milestone: 'B 轮融资', theme: '规模化', target: 2100, startCash: 60, startBudget: 95, maintenance: 12 },
  { id: 3, milestone: 'C 轮融资', theme: '抢市场', target: 3800, startCash: 80, startBudget: 150, maintenance: 18 },
]

export const STAGES = [
  { id: 1, key: 'angel',   name: '天使轮', threshold: 0,     entryGrant: 30, theme: '起步' },
  { id: 2, key: 'seed',    name: '种子轮', threshold: 300,   entryGrant: 25, theme: '产品验证' },
  { id: 3, key: 'seriesA', name: 'A 轮',   threshold: 1000,  entryGrant: 50, theme: '规模化' },
  { id: 4, key: 'seriesB', name: 'B 轮',   threshold: 2500,  entryGrant: 100, theme: '增长' },
  { id: 5, key: 'seriesC', name: 'C 轮',   threshold: 5000,  entryGrant: 200, theme: '扩张' },
  { id: 6, key: 'seriesD', name: 'D 轮',   threshold: 10000, entryGrant: 400, theme: '深耕' },
  { id: 7, key: 'ipo',     name: 'IPO',     threshold: 20000, entryGrant: 700, theme: '上市' },
  { id: 8, key: 'giant',   name: '千亿',    threshold: 40000, entryGrant: 1200, theme: '巨头' },
  { id: 9, key: 'first',   name: '行业第一', threshold: 80000, entryGrant: 2000, theme: '终极' },
]

export const RARITY_TABLE = {
  common:    { baseBurn: 1, extraBurn: 0, assetValue: 5,   bmMonthlyCost: 2, bmAssetValue: 8   },
  rare:      { baseBurn: 2, extraBurn: 1, assetValue: 15,  bmMonthlyCost: 4, bmAssetValue: 25  },
  elite:     { baseBurn: 3, extraBurn: 1, assetValue: 30,  bmMonthlyCost: 6, bmAssetValue: 50  },
  epic:      { baseBurn: 4, extraBurn: 2, assetValue: 50,  bmMonthlyCost: 8, bmAssetValue: 80  },
  legendary: { baseBurn: 7, extraBurn: 4, assetValue: 150, bmMonthlyCost: 14, bmAssetValue: 240 },
}

export const EVENTS = [
  {
    id: 'angel-capital',
    name: '天使融资到账',
    tone: '增益',
    description: '投资人提前打款，运营窗口更宽。',
    effectLines: ['本月现金 +¥10', '本月招聘市场 +1'],
    cashDelta: 10,
    recruitExtra: 1,
    incomeMultiplier: 1,
    maintenanceMultiplier: 1,
  },
  {
    id: 'customer-consulting',
    name: '客户咨询',
    tone: '增益',
    description: '一批高意向客户主动找上门。',
    effectLines: ['本月产线收入 +15%', '销售相邻更容易放大'],
    cashDelta: 0,
    recruitExtra: 0,
    incomeMultiplier: 1.15,
    maintenanceMultiplier: 1,
  },
  {
    id: 'hiring-season',
    name: '招聘旺季',
    tone: '机会',
    description: '候选人质量和数量同步上升。',
    effectLines: ['招聘市场 +2', '战略预算不变'],
    cashDelta: 0,
    recruitExtra: 2,
    incomeMultiplier: 1,
    maintenanceMultiplier: 1,
  },
  {
    id: 'team-conflict',
    name: '团队冲突',
    tone: '风险',
    description: '沟通成本升高，管理资源被消耗。',
    effectLines: ['本月 AP 上限 -2', '产线仍可正常结算'],
    cashDelta: 0,
    apDelta: -2,
    recruitExtra: 0,
    incomeMultiplier: 1,
    maintenanceMultiplier: 1,
  },
  {
    id: 'industry-tailwind',
    name: '行业利好',
    tone: '增益',
    description: '市场窗口打开，所有收入被放大。',
    effectLines: ['本月 ¥ 收入 +20%'],
    cashDelta: 0,
    recruitExtra: 0,
    incomeMultiplier: 1.2,
    maintenanceMultiplier: 1,
  },
  {
    id: 'cash-crunch',
    name: '现金流危机',
    tone: '风险',
    description: '供应商账期收紧，维持费压力上升。',
    effectLines: ['本月维持费 x2', '律师/外包可免除'],
    cashDelta: 0,
    recruitExtra: 0,
    incomeMultiplier: 1,
    maintenanceMultiplier: 2,
  },

  // ============================================================================
  // M2.1b 补事件 +24 张 (总 30 张), 加强戏剧化波动
  // ============================================================================

  // ---- 增益类 +8 ----
  {
    id: 'media-spotlight',
    name: '媒体曝光',
    tone: '增益',
    description: '一篇深度报道点燃公众关注。',
    effectLines: ['本月收入 +30%'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 1.3, maintenanceMultiplier: 1,
  },
  {
    id: 'rd-bonanza',
    name: '风口产业',
    tone: '增益',
    description: '风口吹起，研发卡分获横财。',
    effectLines: ['本月研发部 ×2'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 1.2, maintenanceMultiplier: 1,
    deptBoost: { R: 2 },
  },
  {
    id: 'year-end-bonus',
    name: '跨年红利',
    tone: '增益',
    description: '跨年财务结余反哺运营。',
    effectLines: ['本月维持费 -100%'],
    cashDelta: 5, recruitExtra: 0,
    incomeMultiplier: 1, maintenanceMultiplier: 0,
  },
  {
    id: 'gov-subsidy',
    name: '政府补贴',
    tone: '增益',
    description: '高新技术企业认证下来了。',
    effectLines: ['立即 +¥30'],
    cashDelta: 30, recruitExtra: 0,
    incomeMultiplier: 1, maintenanceMultiplier: 1,
  },
  {
    id: 'competitor-collapse',
    name: '友商内乱',
    tone: '增益',
    description: '主要竞品高管出走，客户外溢。',
    effectLines: ['本月销售部 ×1.5'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 1.1, maintenanceMultiplier: 1,
    deptBoost: { S: 1.5 },
  },
  {
    id: 'big-client',
    name: '大客户签约',
    tone: '增益',
    description: '世界 500 强 LOGO 入手。',
    effectLines: ['立即 +¥50'],
    cashDelta: 50, recruitExtra: 0,
    incomeMultiplier: 1, maintenanceMultiplier: 1,
  },
  {
    id: 'kol-fire',
    name: '网红营销爆款',
    tone: '增益',
    description: '一条短视频带火品牌。',
    effectLines: ['本月销售相邻 +30%', '收入 +10%'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 1.1, maintenanceMultiplier: 1,
  },
  {
    id: 'industry-award',
    name: '行业奖项',
    tone: '增益',
    description: '年度最佳新锐企业。',
    effectLines: ['本月 ¥ +25%', '招聘市场 +1'],
    cashDelta: 0, recruitExtra: 1,
    incomeMultiplier: 1.25, maintenanceMultiplier: 1,
  },

  // ---- 风险类 +8 ----
  {
    id: 'black-swan',
    name: '黑天鹅事件',
    tone: '风险',
    description: '宏观因素突然恶化。',
    effectLines: ['本月收入 -40%'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 0.6, maintenanceMultiplier: 1,
  },
  {
    id: 'key-employee-quit',
    name: '关键员工离职',
    tone: '风险',
    description: '核心高管被挖去竞品。',
    effectLines: ['本月手牌 -2'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 1, maintenanceMultiplier: 1,
    handDelta: -2,
  },
  {
    id: 'media-crisis',
    name: '媒体危机',
    tone: '风险',
    description: '负面新闻在社交平台发酵。',
    effectLines: ['本月维持费 ×3'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 0.9, maintenanceMultiplier: 3,
  },
  {
    id: 'cashflow-tight',
    name: '现金流紧张',
    tone: '风险',
    description: '应收账款迟迟未到。',
    effectLines: ['立即 -¥20'],
    cashDelta: -20, recruitExtra: 0,
    incomeMultiplier: 1, maintenanceMultiplier: 1,
  },
  {
    id: 'team-burnout',
    name: '团队倦怠',
    tone: '风险',
    description: '连续加班导致效率断崖。',
    effectLines: ['本月 AP 上限 -3'],
    cashDelta: 0, recruitExtra: 0,
    apDelta: -3,
    incomeMultiplier: 1, maintenanceMultiplier: 1,
  },
  {
    id: 'rd-winter',
    name: '行业寒冬',
    tone: '风险',
    description: '资本市场对研发型公司估值打折。',
    effectLines: ['本月研发部 -50%'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 0.85, maintenanceMultiplier: 1,
    deptBoost: { R: 0.5 },
  },
  {
    id: 'customer-churn',
    name: '客户流失',
    tone: '风险',
    description: '一波客户被竞品挖走。',
    effectLines: ['本月销售部 -40%'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 0.9, maintenanceMultiplier: 1,
    deptBoost: { S: 0.6 },
  },
  {
    id: 'policy-tighten',
    name: '政策收紧',
    tone: '风险',
    description: '行业监管文件下来了。',
    effectLines: ['本月手牌上限 -2', '维持费 +50%'],
    cashDelta: 0, recruitExtra: 0,
    handLimitDelta: -2,
    incomeMultiplier: 1, maintenanceMultiplier: 1.5,
  },

  // ---- 机会类 +4 ----
  {
    id: 'industry-conference',
    name: '行业大会',
    tone: '机会',
    description: '行业人脉集中曝光的好时机。',
    effectLines: ['招聘市场 +3'],
    cashDelta: 0, recruitExtra: 3,
    incomeMultiplier: 1, maintenanceMultiplier: 1,
  },
  {
    id: 'vc-tailwind',
    name: '投融资风口',
    tone: '机会',
    description: '风险资本疯狂涌入本赛道。',
    effectLines: ['立即 +💰20'],
    cashDelta: 0, recruitExtra: 0,
    budgetDelta: 20,
    incomeMultiplier: 1, maintenanceMultiplier: 1,
  },
  {
    id: 'campus-season',
    name: '校招季',
    tone: '机会',
    description: '应届生集中入职的窗口。',
    effectLines: ['本月抽牌 +3'],
    cashDelta: 0, recruitExtra: 0,
    drawDelta: 3,
    incomeMultiplier: 1, maintenanceMultiplier: 1,
  },
  {
    id: 'internal-startup',
    name: '内部创业',
    tone: '机会',
    description: '抽出一个团队孵化新业务。',
    effectLines: ['本月 AP 上限 +3', '维持费 +50%'],
    cashDelta: 0, recruitExtra: 0,
    apDelta: 3,
    incomeMultiplier: 1.1, maintenanceMultiplier: 1.5,
  },

  // ---- 戏剧化 / 中性 +4 ----
  {
    id: 'investor-visit',
    name: '投资人来访',
    tone: '机会',
    description: '一切都要光鲜亮丽。',
    effectLines: ['本月 AP +3', '维持费 ×1.5'],
    cashDelta: 0, recruitExtra: 0,
    apDelta: 3,
    incomeMultiplier: 1, maintenanceMultiplier: 1.5,
  },
  {
    id: 'team-building',
    name: '团建活动',
    tone: '机会',
    description: '加深感情，但耽误一两天工作。',
    effectLines: ['本月 AP -1', '产出 +25%'],
    cashDelta: 0, recruitExtra: 0,
    apDelta: -1,
    incomeMultiplier: 1.25, maintenanceMultiplier: 1,
  },
  {
    id: 'overtime-season',
    name: '加班冲刺季',
    tone: '机会',
    description: '关键节点全员加班。',
    effectLines: ['维持费 ×2', '收入 ×1.5'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 1.5, maintenanceMultiplier: 2,
  },
  {
    id: 'remote-work',
    name: '远程办公',
    tone: '机会',
    description: '居家办公，灵活但松散。',
    effectLines: ['手牌上限 +2', '招聘市场 -1'],
    cashDelta: 0, recruitExtra: -1,
    handLimitDelta: 2,
    incomeMultiplier: 1, maintenanceMultiplier: 0.8,
  },
]

export const BOSS_EVENTS = [
  {
    id: 'boss-series-a-roadshow',
    name: 'Boss · A 轮路演',
    tone: 'Boss',
    description: '投资人只看核心位置有没有能扛场的人。',
    effectLines: ['关末检查: P3 必须是经理级或以上', '不满足则本关无法达标'],
    incomeMultiplier: 1,
    maintenanceMultiplier: 1,
    bossRule: { type: 'p3_min_tier', minTier: '经理' },
  },
  {
    id: 'boss-series-b-diligence',
    name: 'Boss · B 轮尽调',
    tone: 'Boss',
    description: '尽调团队进场，成本翻倍，但好数据会被放大。',
    effectLines: ['本月收入 +30%', '本月维持费 x2'],
    incomeMultiplier: 1.3,
    maintenanceMultiplier: 2,
    bossRule: { type: 'none' },
  },
  {
    id: 'boss-series-c-negotiation',
    name: 'Boss · C 轮谈判',
    tone: 'Boss',
    description: '谈判桌只留最关键的人，临场可用手牌骤减。',
    effectLines: ['进入 Boss 月时手牌 -3', '被移走的牌回到牌堆'],
    incomeMultiplier: 1,
    maintenanceMultiplier: 1,
    handDelta: -3,
    bossRule: { type: 'none' },
  },
]

export const SMALL_AFFIXES = [
  { id: 'AFF_S_01', name: '加班狂', effects: ['BASE_OUTPUT: +30%'] },
  { id: 'AFF_S_02', name: '性价比', effects: ['COST: -40%'] },
  { id: 'AFF_S_03', name: '资深', effects: ['COST: +50%', 'BASE_OUTPUT: +25%'] },
  { id: 'AFF_S_05', name: '团魂', effects: ['SAME_DEPT_ADJ_EXTRA: +10%'] },
  { id: 'AFF_S_07', name: '完美主义', effects: ['SELF_IF_P3: +25%'] },
  { id: 'AFF_S_08', name: '收割者', effects: ['SELF_IF_P5: +30%'] },
  { id: 'AFF_S_10', name: '学霸', effects: ['SELF_IF_ADJ_FUN: +20%'] },
]

export const LARGE_AFFIXES = [
  { id: 'AFF_L_02', name: '双倍工作', effects: ['NO_COOLDOWN'] },
  { id: 'AFF_L_05', name: '化学反应', effects: ['SAME_DEPT_ADJ_EXTRA: +25%'] },
  { id: 'AFF_L_08', name: '大佬光环', effects: ['LINE_ALL: +15%'] },
  { id: 'AFF_L_10', name: '一颗螺丝钉', effects: ['LINE_ALL: +12%'] },
  { id: 'AFF_L_11', name: '跨界鬼才', effects: ['IF_ALL_THREE_DEPT_IN_LINE: LINE_ALL: x1.5'] },
]

export const CARD_TEMPLATES = [
  {
    id: 'EMP_R_01',
    name: '研发专员',
    type: 'emp',
    dept: 'R',
    tier: '专员',
    rarity: 'common',
    unlockLevel: 1,
    ap: 1,
    costSpec: '5 ±10%',
    baseOutputSpec: '20 ±10%',
    effects: ['RIGHT: +10% ±10%'],
    flavor: '刚毕业的小伙子，加班贼狠',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_02',
    name: '研发经理',
    type: 'emp',
    dept: 'R',
    tier: '经理',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '11 ±10%',
    baseOutputSpec: '45 ±10%',
    effects: ['RIGHT: +25% ±10%'],
    flavor: '技术骨干升上来的，能写代码也能带人',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_03',
    name: '研发总监',
    type: 'emp',
    dept: 'R',
    tier: '总监',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 4,
    costSpec: '22 ±15%',
    baseOutputSpec: '85 ±15%',
    effects: ['RIGHT: +40% ±15%', 'SELF_IF_P1: +20%'],
    flavor: '技术线最高决策者，路线图全靠他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_04',
    name: '算法专家',
    type: 'emp',
    dept: 'R',
    tier: '专员',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 2,
    costSpec: '15 ±15%',
    baseOutputSpec: '35 ±15%',
    effects: ['SELF_IF_RIGHT_FUN: x1.5', 'RIGHT: +15% ±15%'],
    flavor: '懂数据、懂模型，但不太会说话',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_05',
    name: '全栈工程师',
    type: 'emp',
    dept: 'R',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 3,
    costSpec: '17 ±15%',
    baseOutputSpec: '55 ±15%',
    effects: ['BOTH: +15% ±15%'],
    flavor: '一个人顶三个用，但跳槽风险大',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_06',
    name: '架构师',
    type: 'emp',
    dept: 'R',
    tier: '总监',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 4,
    costSpec: '25 ±15%',
    baseOutputSpec: '75 ±15%',
    effects: ['SAME_DEPT_ADJ: +30%', 'RIGHT: +20% ±15%'],
    flavor: '图画得比代码多，但你不能没有他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_07',
    name: '技术 VP',
    type: 'emp',
    dept: 'R',
    tier: 'VP',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 5,
    costSpec: '35 ±20%',
    baseOutputSpec: '120 ±20%',
    effects: ['LINE_ALL_R: +25%', 'RIGHT: +30% ±20%'],
    flavor: '技术线副总裁，话不多但说话顶用',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_08',
    name: '首席科学家',
    type: 'emp',
    dept: 'R',
    tier: 'VP',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 5,
    costSpec: '45 ±25%',
    baseOutputSpec: '140 ±25%',
    effects: ['SELF_IF_P3: BOTH: +40%', 'MONTH_STAR_RATE: +5%'],
    flavor: '顶着 PhD 学位的明星，估值看脸的关键',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_09',
    name: '极客实习生',
    type: 'emp',
    dept: 'R',
    tier: '专员',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 2,
    costSpec: '10 ±20%',
    baseOutputSpec: '38 ±20%',
    effects: ['RIGHT: +30% ±20%', 'TRIGGER: SELF_IF_LEFT_DEPT_R: SELF: x2'],
    flavor: '成本极低产出极高，但容易被挖',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_01',
    name: '销售专员',
    type: 'emp',
    dept: 'S',
    tier: '专员',
    rarity: 'common',
    unlockLevel: 1,
    ap: 1,
    costSpec: '5 ±10%',
    baseOutputSpec: '20 ±10%',
    effects: ['LEFT: +10% ±10%'],
    flavor: '电话打到嗓子哑，提成是动力',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_02',
    name: '销售经理',
    type: 'emp',
    dept: 'S',
    tier: '经理',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '11 ±10%',
    baseOutputSpec: '45 ±10%',
    effects: ['LEFT: +20% ±10%'],
    flavor: '带一支小队，月度冠军常客',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_03',
    name: '销售总监',
    type: 'emp',
    dept: 'S',
    tier: '总监',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 4,
    costSpec: '22 ±15%',
    baseOutputSpec: '85 ±15%',
    effects: ['LEFT: +35% ±15%', 'SELF_IF_P5: x1.5'],
    flavor: '客户全在他手机里，公司离不开他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_04',
    name: '大客户经理',
    type: 'emp',
    dept: 'S',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 3,
    costSpec: '17 ±15%',
    baseOutputSpec: '55 ±15%',
    effects: ['LEFT: +15% ±15%', 'SELF_IF_LEFT_DEPT_R: x1.4'],
    flavor: '专啃硬骨头，订单一签就是几百万',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_05',
    name: 'BD 专员',
    type: 'emp',
    dept: 'S',
    tier: '专员',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 2,
    costSpec: '13 ±15%',
    baseOutputSpec: '30 ±15%',
    effects: ['LEFT: +12% ±15%', 'MONTH_BONUS: +¥3'],
    flavor: 'BD 全靠人脉，吃饭喝酒签合作',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_06',
    name: '电商运营',
    type: 'emp',
    dept: 'S',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '18 ±15%',
    baseOutputSpec: '50 ±15%',
    effects: ['BOTH: +12% ±15%', 'TRIGGER: SELF_IF_LINE_HAS_FUN: x1.3'],
    flavor: 'GMV 主义者，永远在 ABtest',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_07',
    name: '销售 VP',
    type: 'emp',
    dept: 'S',
    tier: 'VP',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 5,
    costSpec: '35 ±20%',
    baseOutputSpec: '120 ±20%',
    effects: ['LINE_ALL_S: +25%', 'LEFT: +30% ±20%'],
    flavor: '销售一把手，KPI 拍板靠他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_08',
    name: '销售之神',
    type: 'emp',
    dept: 'S',
    tier: 'VP',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 5,
    costSpec: '45 ±25%',
    baseOutputSpec: '140 ±25%',
    effects: ['SELF_IF_P5: SELF: x2.5', 'LEFT: +30% ±25%'],
    flavor: '传说级销售，开口就是大单',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_09',
    name: '客户成功',
    type: 'emp',
    dept: 'S',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '17 ±15%',
    baseOutputSpec: '50 ±15%',
    effects: ['LEFT: +18% ±15%', 'SAME_DEPT_ADJ: +¥2'],
    flavor: '续约率王者，老客户都认他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_01',
    name: '运营专员',
    type: 'emp',
    dept: 'O',
    tier: '专员',
    rarity: 'common',
    unlockLevel: 1,
    ap: 1,
    costSpec: '5 ±10%',
    baseOutputSpec: '22 ±10%',
    effects: ['SAME_DEPT_ADJ: +¥1'],
    flavor: 'Excel 大师，表格能开花',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_02',
    name: '运营经理',
    type: 'emp',
    dept: 'O',
    tier: '经理',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '11 ±10%',
    baseOutputSpec: '48 ±10%',
    effects: ['SAME_DEPT_ADJ: +¥2', 'BOTH: +10% ±10%'],
    flavor: '流程优化狂魔，省钱的能手',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_03',
    name: '运营总监',
    type: 'emp',
    dept: 'O',
    tier: '总监',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 4,
    costSpec: '22 ±15%',
    baseOutputSpec: '85 ±15%',
    effects: ['SAME_DEPT_ADJ: +¥3', 'SELF_IF_P3: BOTH: +25%'],
    flavor: '公司大管家，老板甩手掌柜全靠他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_04',
    name: 'HR 经理',
    type: 'emp',
    dept: 'O',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 3,
    costSpec: '16 ±15%',
    baseOutputSpec: '45 ±15%',
    effects: ['LINE_ALL: +8% ±15%', 'MONTH_BONUS: +¥2'],
    flavor: '招聘留人都是他，但绩效面谈让人怕',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_05',
    name: '财务经理',
    type: 'emp',
    dept: 'O',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 3,
    costSpec: '18 ±15%',
    baseOutputSpec: '40 ±15%',
    effects: ['MONTH_BONUS: +¥5', 'BOTH: +8% ±15%'],
    flavor: '管钱袋子的人，老板真正的朋友',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_06',
    name: '项目经理 PM',
    type: 'emp',
    dept: 'O',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '17 ±15%',
    baseOutputSpec: '50 ±15%',
    effects: ['BOTH: +20% ±15%', 'TRIGGER: SELF_IF_LEFT_DEPT_R_AND_RIGHT_DEPT_S: SELF: x1.5'],
    flavor: '甘特图战神，跨部门翻译机',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_07',
    name: '运营 VP / COO',
    type: 'emp',
    dept: 'O',
    tier: 'VP',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 5,
    costSpec: '38 ±20%',
    baseOutputSpec: '115 ±20%',
    effects: ['LINE_ALL: +15%', 'MONTH_BONUS: +¥10'],
    flavor: '首席运营官，公司日常运转的中枢',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_08',
    name: '行政总管',
    type: 'emp',
    dept: 'O',
    tier: '总监',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 4,
    costSpec: '20 ±15%',
    baseOutputSpec: '70 ±15%',
    effects: ['MONTH_NO_MAINTAIN', 'BOTH: +10% ±15%'],
    flavor: '省下的就是赚到的',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_09',
    name: '数据分析师',
    type: 'emp',
    dept: 'O',
    tier: '专员',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 2,
    costSpec: '13 ±15%',
    baseOutputSpec: '32 ±15%',
    effects: ['BOTH: +18% ±15%', 'TRIGGER: SELF_IF_ADJ_FUN: SELF: x1.4'],
    flavor: 'SQL 写得比情书还多，数字驱动决策',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_01',
    name: '市场调研',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '7 ±10%',
    baseOutputSpec: '0',
    effects: ['BOTH: +25% ±10%'],
    flavor: '了解客户才能搞定客户',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'FUN_02',
    name: '产品冲刺',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 1,
    ap: 3,
    costSpec: '9 ±10%',
    baseOutputSpec: '0',
    effects: ['ADJ_R: x2 ±10%'],
    flavor: '全部门拼一把，发版日就是验货日',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'FUN_03',
    name: '团队建设',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '8 ±10%',
    baseOutputSpec: '0',
    effects: ['LINE_ALL: +¥15 ±10%'],
    flavor: '团建不是吃饭，是凝聚力投资',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'FUN_04',
    name: '产品推广',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 1,
    ap: 3,
    costSpec: '9 ±10%',
    baseOutputSpec: '0',
    effects: ['ADJ_S: x2 ±10%'],
    flavor: '酒香也怕巷子深，推广要趁早',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'FUN_05',
    name: '数据分析',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 2,
    ap: 2,
    costSpec: '7 ±10%',
    baseOutputSpec: '0',
    effects: ['LEFT: +30% ±10%'],
    flavor: '用数据说话，向上汇报必备',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_06',
    name: '流程优化',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 2,
    ap: 2,
    costSpec: '7 ±10%',
    baseOutputSpec: '0',
    effects: ['RIGHT: +30% ±10%'],
    flavor: '把繁琐变简单，把简单变高效',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_07',
    name: '跨部门协作',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '13 ±15%',
    baseOutputSpec: '0',
    effects: ['TRIGGER: LEFT_DEPT != RIGHT_DEPT: BOTH: +40% ±15%'],
    flavor: '墙太厚要敲掉，孤岛太多要修桥',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_08',
    name: 'OKR 制定',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '13 ±15%',
    baseOutputSpec: '0',
    effects: ['LINE_ALL: +15% ±15%', 'MONTH_STAR_RATE: +3%'],
    flavor: '目标对齐了，效率才有意义',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_09',
    name: '加班动员',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 2,
    ap: 2,
    costSpec: '7 ±10%',
    baseOutputSpec: '0',
    effects: ['LINE_ALL: +20% ±10%'],
    flavor: '冲一波，但下个月别怪我',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_10',
    name: '品牌建设',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '15 ±15%',
    baseOutputSpec: '0',
    effects: ['BOTH: +20% ±15%', 'MONTH_STAR_RATE: +8%'],
    flavor: '品牌即资产，长期主义的体现',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_11',
    name: '用户运营活动',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '14 ±15%',
    baseOutputSpec: '0',
    effects: ['ADJ_S: +50% ±15%', 'MONTH_BONUS: +¥10'],
    flavor: '拉新促活，私域引流的标配',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_12',
    name: '技术债务清理',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'rare',
    unlockLevel: 4,
    ap: 3,
    costSpec: '14 ±15%',
    baseOutputSpec: '0',
    effects: ['ADJ_R: +50% ±15%'],
    flavor: '前人欠的债，后人还，但还完爽',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_01',
    name: '律师事务所',
    type: 'srv',
    dept: 'NONE',
    tier: '基础',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '8 ±10%',
    baseOutputSpec: '0',
    effects: ['MONTH_NO_MAINTAIN'],
    flavor: '合同审查 + 风险规避，省钱的法宝',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'SRV_02',
    name: '税务筹划',
    type: 'srv',
    dept: 'NONE',
    tier: '基础',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '8 ±10%',
    baseOutputSpec: '0',
    effects: ['MONTH_STAR_RATE: +5%'],
    flavor: '合法节税是企业必修课',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_03',
    name: '外部咨询',
    type: 'srv',
    dept: 'NONE',
    tier: '进阶',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 4,
    costSpec: '19 ±15%',
    baseOutputSpec: '0',
    effects: ['LINE_XMULT: x1.3 ±15%'],
    flavor: 'Mck.ey 一份报告，半年战略不愁',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_04',
    name: '融资顾问',
    type: 'srv',
    dept: 'NONE',
    tier: '进阶',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 3,
    costSpec: '15 ±15%',
    baseOutputSpec: '0',
    effects: ['MONTH_BONUS: +¥15 ±15%', 'MONTH_STAR_RATE: +3%'],
    flavor: '对接 VC、修 BP，专业的人做专业的事',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_05',
    name: '管理咨询',
    type: 'srv',
    dept: 'NONE',
    tier: '顶级',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 5,
    costSpec: '32 ±20%',
    baseOutputSpec: '0',
    effects: ['MONTH_AP: +5'],
    flavor: '组织架构 + 流程再造的大手术',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_06',
    name: '战略顾问',
    type: 'srv',
    dept: 'NONE',
    tier: '顶级',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 5,
    costSpec: '32 ±20%',
    baseOutputSpec: '0',
    effects: ['LINE_ALL: +30% ±20%'],
    flavor: '看远一些，走稳一些',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_07',
    name: 'PR 公关',
    type: 'srv',
    dept: 'NONE',
    tier: '进阶',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '15 ±15%',
    baseOutputSpec: '0',
    effects: ['MONTH_STAR_RATE: +10%'],
    flavor: '口碑、热度、声誉，都是真金白银',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_08',
    name: 'HR 外包',
    type: 'srv',
    dept: 'NONE',
    tier: '基础',
    rarity: 'common',
    unlockLevel: 2,
    ap: 2,
    costSpec: '9 ±10%',
    baseOutputSpec: '0',
    effects: ['MONTH_NO_MAINTAIN', 'BOTH: +5% ±10%'],
    flavor: '把杂活外包出去，专注主业',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_09',
    name: '投行顾问',
    type: 'srv',
    dept: 'NONE',
    tier: '顶级',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 5,
    costSpec: '40 ±25%',
    baseOutputSpec: '0',
    effects: ['MONTH_BONUS: +¥30 ±25%', 'MONTH_STAR_RATE: +15%'],
    flavor: '上市路上的必经合作伙伴',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_10',
    name: '法律团队',
    type: 'srv',
    dept: 'NONE',
    tier: '进阶',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '16 ±15%',
    baseOutputSpec: '0',
    effects: ['MONTH_NO_MAINTAIN', 'LINE_ALL: +10% ±15%'],
    flavor: '升级版律师，覆盖知识产权、并购',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  // ===== 传奇卡 (仅董事会会议·投资部刷出, 详见 BOARD_MEETING_DESIGN.md §3) =====
  {
    id: 'LEG_R_01',
    name: '诺贝尔奖得主',
    type: 'emp',
    dept: 'R',
    tier: 'CXO',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 5,
    costSpec: '60 ±30%',
    baseOutputSpec: '180 ±30%',
    effects: ['SELF_IF_P3: BOTH: x2', 'LINE_ALL: +20% ±30%', 'MONTH_STAR_RATE: +10%'],
    flavor: '行业天花板，能让对手直接出局',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'LEG_S_01',
    name: '销冠之神',
    type: 'emp',
    dept: 'S',
    tier: 'CXO',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 5,
    costSpec: '55 ±30%',
    baseOutputSpec: '170 ±30%',
    effects: ['SAME_DEPT_S_ADJ: +50%', 'LINE_ALL_S_X: x1.5', 'MONTH_BONUS: +¥50 ±30%'],
    flavor: '一年只服务一家公司',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'LEG_O_01',
    name: '六西格玛大师',
    type: 'emp',
    dept: 'O',
    tier: 'CXO',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 5,
    costSpec: '50 ±30%',
    baseOutputSpec: '150 ±30%',
    effects: ['LINE_ALL: x1.4', 'MONTH_NO_MAINTAIN', 'SAME_DEPT_O_ADJ: +30%'],
    flavor: '所到之处皆为黑带',
    inStarterDeck: false,
    inRecruitPool: false,
  },

  // ============================================================================
  // M2.1b 补卡: 精英 +6 / 史诗 +12 / 传奇 +7
  // 设计原则: 不再是 RIGHT/LEFT +X% 的同形, 强调"机制颠覆"
  // ============================================================================

  // ---- 精英 +6 (每部门 2 张) ----
  {
    id: 'EMP_R_10',
    name: '黑客马拉松',
    type: 'emp',
    dept: 'R',
    tier: '专员',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 3,
    costSpec: '18 ±20%',
    baseOutputSpec: '42 ±20%',
    effects: ['ADJ_R: +60% ±20%', 'SELF_IF_LEFT_DEPT_R: SELF: x1.5'],
    flavor: '48 小时内造出 demo 的疯子',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_11',
    name: '专利律师',
    type: 'emp',
    dept: 'R',
    tier: '经理',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 3,
    costSpec: '20 ±20%',
    baseOutputSpec: '38 ±20%',
    effects: ['LINE_ALL_R: +¥8 ±20%', 'MONTH_STAR_RATE: +5%'],
    flavor: '把每一行代码都变成护城河',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_10',
    name: '展会专家',
    type: 'emp',
    dept: 'S',
    tier: '经理',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 3,
    costSpec: '18 ±20%',
    baseOutputSpec: '40 ±20%',
    effects: ['LINE_ALL_S: +¥8 ±20%', 'MONTH_BONUS: +¥10'],
    flavor: '一场展会换三个 LOI',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_11',
    name: '合伙人销售',
    type: 'emp',
    dept: 'S',
    tier: '总监',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 4,
    costSpec: '24 ±20%',
    baseOutputSpec: '55 ±20%',
    effects: ['SAME_DEPT_ADJ: +40%', 'LEFT: +30% ±20%'],
    flavor: '客户专找他签单',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_10',
    name: '精益顾问',
    type: 'emp',
    dept: 'O',
    tier: '经理',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 3,
    costSpec: '18 ±20%',
    baseOutputSpec: '30 ±20%',
    effects: ['MONTH_NO_MAINTAIN', 'LINE_ALL: +10% ±15%'],
    flavor: '砍掉一切不创造价值的步骤',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_11',
    name: '数据科学家',
    type: 'emp',
    dept: 'O',
    tier: '总监',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 4,
    costSpec: '24 ±20%',
    baseOutputSpec: '50 ±20%',
    effects: ['SELF_IF_P3: BOTH: +30%', 'BOTH: +15% ±20%'],
    flavor: 'AB Test 跑 24 小时就拍板',
    inStarterDeck: false,
    inRecruitPool: true,
  },

  // ---- 史诗 +12 (每部门 4 张) ----
  // R 部门 4 张
  {
    id: 'EMP_R_12',
    name: 'CTO',
    type: 'emp',
    dept: 'R',
    tier: 'CXO',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 5,
    costSpec: '48 ±25%',
    baseOutputSpec: '120 ±25%',
    effects: ['LINE_ALL_R: x1.5', 'SELF_IF_P3: BOTH: +50%'],
    flavor: '架构、招聘、布道一肩挑',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_13',
    name: 'AI 研究员',
    type: 'emp',
    dept: 'R',
    tier: 'VP',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 4,
    costSpec: '42 ±25%',
    baseOutputSpec: '100 ±25%',
    effects: ['SELF_IF_P3: LINE_ALL: +30%', 'BOTH: +20% ±25%'],
    flavor: '论文产出比商业产出还重要',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_14',
    name: '开源大牛',
    type: 'emp',
    dept: 'R',
    tier: '总监',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 3,
    costSpec: '36 ±25%',
    baseOutputSpec: '90 ±25%',
    effects: ['SELF_IF_LEFT_DEPT_R: SELF: x2', 'RIGHT: +35% ±25%'],
    flavor: 'GitHub 上有 10k+ stars',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_15',
    name: '极客天才',
    type: 'emp',
    dept: 'R',
    tier: '专员',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 2,
    costSpec: '24 ±25%',
    baseOutputSpec: '70 ±25%',
    effects: ['SELF_IF_LINE_HAS_FUN: SELF: x2', 'ADJ_R: +40% ±25%'],
    flavor: '低薪高产出的代码狂人',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  // S 部门 4 张
  {
    id: 'EMP_S_12',
    name: 'CMO',
    type: 'emp',
    dept: 'S',
    tier: 'CXO',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 5,
    costSpec: '48 ±25%',
    baseOutputSpec: '120 ±25%',
    effects: ['LINE_ALL_S: x1.5', 'MONTH_BONUS: +¥20'],
    flavor: '砸品牌就为了一个数字',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_13',
    name: 'KOL 矩阵',
    type: 'emp',
    dept: 'S',
    tier: 'VP',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 4,
    costSpec: '40 ±25%',
    baseOutputSpec: '95 ±25%',
    effects: ['SELF_IF_P5: SELF: x3', 'LEFT: +40% ±25%'],
    flavor: '一条视频带火一个品类',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_14',
    name: '金牌销售',
    type: 'emp',
    dept: 'S',
    tier: '总监',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 3,
    costSpec: '35 ±25%',
    baseOutputSpec: '85 ±25%',
    effects: ['LEFT: +50% ±25%', 'SAME_DEPT_ADJ: +30%'],
    flavor: '靠 Excel 和酒桌打天下',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_15',
    name: '客户成功 VP',
    type: 'emp',
    dept: 'S',
    tier: 'VP',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 4,
    costSpec: '38 ±25%',
    baseOutputSpec: '80 ±25%',
    effects: ['LINE_ALL: +¥15 ±25%', 'BOTH: +25% ±25%'],
    flavor: 'NPS 是公司的生命线',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  // O 部门 4 张
  {
    id: 'EMP_O_12',
    name: 'COO',
    type: 'emp',
    dept: 'O',
    tier: 'CXO',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 5,
    costSpec: '46 ±25%',
    baseOutputSpec: '110 ±25%',
    effects: ['LINE_ALL: x1.4', 'MONTH_NO_MAINTAIN'],
    flavor: 'CEO 不在时她就是 CEO',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_13',
    name: '精益大师',
    type: 'emp',
    dept: 'O',
    tier: 'VP',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 4,
    costSpec: '40 ±25%',
    baseOutputSpec: '95 ±25%',
    effects: ['MONTH_NO_MAINTAIN', 'LINE_ALL: +20% ±25%'],
    flavor: '砍掉一半员工产出反而翻倍',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_14',
    name: 'OD 顾问',
    type: 'emp',
    dept: 'O',
    tier: '总监',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 3,
    costSpec: '34 ±25%',
    baseOutputSpec: '85 ±25%',
    effects: ['SAME_DEPT_ADJ: +60%', 'LINE_ALL: +5%'],
    flavor: '组织设计、KPI 重构、文化变革',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_15',
    name: '财务总监',
    type: 'emp',
    dept: 'O',
    tier: '总监',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 4,
    costSpec: '38 ±25%',
    baseOutputSpec: '75 ±25%',
    effects: ['MONTH_BONUS: +¥25 ±25%', 'MONTH_NO_MAINTAIN'],
    flavor: '盘活每一分钱',
    inStarterDeck: false,
    inRecruitPool: true,
  },

  // ---- 传奇 +7 (4 张员工 + 3 张跨类) ----
  {
    id: 'LEG_R_02',
    name: '图灵奖得主',
    type: 'emp',
    dept: 'R',
    tier: 'CXO',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 5,
    costSpec: '70 ±30%',
    baseOutputSpec: '200 ±30%',
    effects: ['LINE_ALL_R: x2', 'SELF_IF_P3: BOTH: x2'],
    flavor: '诺奖得主只是他的学生',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'LEG_S_02',
    name: '乔布斯式 CEO',
    type: 'emp',
    dept: 'S',
    tier: 'CXO',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 5,
    costSpec: '68 ±30%',
    baseOutputSpec: '190 ±30%',
    effects: ['LINE_ALL: x1.5', 'SELF_IF_P3: LINE_ALL: +50%'],
    flavor: '产品 + 营销 + 现实扭曲力场',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'LEG_O_02',
    name: '德鲁克再世',
    type: 'emp',
    dept: 'O',
    tier: 'CXO',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 4,
    costSpec: '60 ±30%',
    baseOutputSpec: '150 ±30%',
    effects: ['MONTH_NO_MAINTAIN', 'LINE_ALL: +¥30 ±30%'],
    flavor: '管理学之父在世',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'LEG_M_01',
    name: '连续创业者',
    type: 'emp',
    dept: 'NONE',
    tier: 'CXO',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 5,
    costSpec: '65 ±30%',
    baseOutputSpec: '170 ±30%',
    effects: ['LINE_ALL: x1.6', 'IF_ALL_THREE_DEPT_IN_LINE: LINE_XMULT: x1.5'],
    flavor: '已经卖出过 3 家独角兽',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'SRV_LEG_01',
    name: '麦肯锡战略',
    type: 'srv',
    dept: 'NONE',
    tier: '顶级',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 5,
    costSpec: '55 ±30%',
    baseOutputSpec: '0',
    effects: ['LINE_XMULT: x2 ±30%', 'MONTH_BONUS: +¥50'],
    flavor: '咨询界的最高荣誉',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'FUN_LEG_01',
    name: '黑天鹅基金',
    type: 'fun',
    dept: 'NONE',
    tier: '顶级',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 4,
    costSpec: '50 ±30%',
    baseOutputSpec: '0',
    effects: ['LINE_XMULT: x3', 'MONTH_BONUS: +¥30'],
    flavor: '反脆弱才是真正的护城河',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'FUN_LEG_02',
    name: '专利墙战略',
    type: 'fun',
    dept: 'NONE',
    tier: '顶级',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 3,
    costSpec: '40 ±30%',
    baseOutputSpec: '0',
    effects: ['BOTH: +60% ±30%', 'LINE_ALL_R: +30%'],
    flavor: '把每个 idea 都申请成专利',
    inStarterDeck: false,
    inRecruitPool: false,
  },
]

// ============================================================================
// 抽卡概率 (drawWeight) - 默认按稀有度分配，可在卡片定义里通过 drawWeight 字段覆写
// ============================================================================
export const DEFAULT_DRAW_WEIGHTS = {
  common: 100,
  rare: 40,
  elite: 12,
  epic: 4,
  legendary: 1,
}

// Mutate templates 一次性补齐 drawWeight 字段，以及 burn/asset 字段
for (const card of CARD_TEMPLATES) {
  if (card.drawWeight == null) {
    card.drawWeight = DEFAULT_DRAW_WEIGHTS[card.rarity] ?? 10
  }
  const rarityInfo = RARITY_TABLE[card.rarity] || RARITY_TABLE.common
  card.baseBurn = card.baseBurn ?? rarityInfo.baseBurn
  card.extraBurn = card.extraBurn ?? rarityInfo.extraBurn
  card.assetValue = card.assetValue ?? rarityInfo.assetValue
}



// ============================================================================
// 关间「董事会会议」数据 (详见 BOARD_MEETING_DESIGN.md)
// ============================================================================

/**
 * 商业模式 (Balatro Joker 类全局 buff) - 40 张
 * hook 类型：onMonthStart / onSettle / onCharge
 * 数量按稀有度逐级递减: common 14 / rare 12 / elite 8 / epic 4 / legendary 2
 *
 * 名字风格：流行管理理论 + 行业黑话 + 大厂模式
 * flavor 字段：hover 时显示的吐槽（保持幽默感）
 */
export const BUSINESS_MODELS = [
  // ============================================================================
  // onMonthStart · 月初触发 (15 张)
  // ============================================================================

  // ---- Common (5) ----
  {
    id: 'BM_01',
    name: '全员 Owner',
    hook: 'onMonthStart',
    payload: { type: 'drawBonus', value: 1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '月初抽牌 +1',
    flavor: '人人都是 Owner，问题来了：谁来当员工？决策很民主，背锅很模糊。德鲁克说的「赋权」不是这个意思。',
  },
  {
    id: 'BM_02',
    name: 'OKR 对齐',
    hook: 'onMonthStart',
    payload: { type: 'apIfHandRich', threshold: 6, value: 1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '月初手牌 ≥6 张时 AP +1',
    flavor: 'Objective 是大家一起写的，Key Result 是老板拍脑袋定的，绩效是 HR 评的。',
  },
  {
    id: 'BM_05',
    name: '差异化定位',
    hook: 'onMonthStart',
    payload: { type: 'handLimitBonus', value: 2 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '月初手牌上限 +2',
    flavor: '波特说要做差异化战略。客户问"你们和别家有什么不同？" 销售答："我们的 PPT 更精美。"',
  },
  {
    id: 'BM_14',
    name: 'PMO',
    hook: 'onMonthStart',
    payload: { type: 'drawBonus', value: 1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '月初抽牌 +1',
    flavor: '"项目管理办公室" = 5 个不写代码不做产品的人，每天追着所有人填表、对齐、复盘、风险评估。',
  },
  {
    id: 'BM_15',
    name: '抓大放小',
    hook: 'onMonthStart',
    payload: { type: 'handLimitBonus', value: 2 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '月初手牌上限 +2',
    flavor: '重要的事先做，次要的事"先放一放"。结果次要的事永远在"放一放"里，重要的事天天换。',
  },

  // ---- Rare (5) ----
  {
    id: 'BM_03',
    name: '降本增效',
    hook: 'onMonthStart',
    payload: { type: 'maintenanceDiscount', value: 0.2 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '维持费 -20%',
    flavor: '降的是别人的本，增的是 KPI 的效。寒冬必备技能，越降越冷。',
  },
  {
    id: 'BM_04',
    name: '精益创业',
    hook: 'onMonthStart',
    payload: { type: 'lineApDiscount', value: 1 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '每条产线 AP -1 (最低 1)',
    flavor: 'MVP 验证完没人用？那就 Pivot。Pivot 完还不行？继续 Pivot。Pivot 12 次后，融资到 B 轮。',
  },
  {
    "id": "BM_16",
    "name": "007",
    "hook": "onMonthStart",
    "payload": {
      "type": "apIfHandRich",
      "threshold": 6,
      "value": 1
    },
    "rarity": "rare",
    "unlockLevel": 4,
    "cost": 13,
    "description": "月初手牌 ≥6 张时 AP +1",
    "flavor": "我说的是大家都知道的知名大帅间谍，不是 24×7 在线，0 点睡 0 点起，0 假期这些。"
  },
  {
    id: 'BM_17',
    name: 'Sprint 冲刺',
    hook: 'onMonthStart',
    payload: { type: 'drawBonus', value: 2 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '月初抽牌 +2',
    flavor: 'Sprint 计划会 2 小时，回顾会 2 小时，写代码 2 小时。剩下时间打卡和填工时表。',
  },
  {
    id: 'BM_18',
    name: '数据驱动',
    hook: 'onMonthStart',
    payload: { type: 'maintenanceDiscount', value: 0.3 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '维持费 -30%',
    flavor: '决策不靠拍脑袋。改了 17 版 dashboard、跑了 23 次 AB 测试之后，还是靠老板拍脑袋。',
  },

  // ---- Elite (3) ----
  {
    id: 'BM_19',
    name: '中台建设',
    hook: 'onMonthStart',
    payload: { type: 'lineApDiscount', value: 2 },
    rarity: 'elite',
    unlockLevel: 4,
    cost: 18,
    description: '每条产线 AP -2 (最低 1)',
    flavor: '把所有部门的能力沉淀到中台。建完业务方不用，再建 2.0，还不用，建 3.0。终于有人用了——是中台自己的人在用。',
  },
  {
    id: 'BM_20',
    name: '起立坐下',
    hook: 'onMonthStart',
    payload: { type: 'drawBonus', value: 2 },
    rarity: 'elite',
    unlockLevel: 4,
    cost: 18,
    description: '月初抽牌 +2',
    flavor: '三个团队同做一个产品，每月汇报现场，老板说"你坐下，你起立，你来讲讲"。胜者通吃，败者解散。',
  },
  {
    id: 'BM_21',
    name: '砍价式管理',
    hook: 'onMonthStart',
    payload: { type: 'maintenanceDiscount', value: 0.5 },
    rarity: 'elite',
    unlockLevel: 4,
    cost: 18,
    description: '维持费 -50%',
    flavor: '没有中层，全是基层。"扁平化管理" = "所有人都直接汇报给老板" = "老板永远在开会"。',
  },

  // ---- Epic (1) ----
  {
    id: 'BM_22',
    name: '凡事 ROI',
    hook: 'onMonthStart',
    payload: { type: 'drawBonus', value: 3 },
    rarity: 'epic',
    unlockLevel: 6,
    cost: 24,
    description: '月初抽牌 +3',
    flavor: '会议要算 ROI，吃饭要算 ROI，上厕所要不要冲水也要算 ROI。HR 谈话之前先算 ROI。',
  },

  // ---- Legendary (1) ----
  {
    id: 'BM_23',
    name: '护城河信徒',
    hook: 'onMonthStart',
    payload: { type: 'handLimitBonus', value: 4 },
    rarity: 'legendary',
    unlockLevel: 7,
    cost: 30,
    description: '月初手牌上限 +4',
    flavor: '在别人贪婪时恐惧，在别人恐惧时贪婪，在他们都迷茫时，买消费品和手机大厂。然后等待 50 年。',
  },

  // ============================================================================
  // onSettle · 结算乘区 (15 张)
  // ============================================================================

  // ---- Common (5) ----
  {
    id: 'BM_06',
    name: '批量涌现',
    hook: 'onSettle',
    payload: { type: 'sameDeptAdjBonus', value: 0.1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '同部门相邻 +10%',
    flavor: '明茨伯格说战略不是规划出来的，是涌现出来的。所以这一年到底干了什么？复盘的时候再编。',
  },
  {
    id: 'BM_08',
    name: '工程师文化',
    hook: 'onSettle',
    payload: { type: 'deptBonus', dept: 'R', value: 0.15 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: 'R 部门 +15%',
    flavor: '你有想法？写个 PRD。你有 PRD？写代码。你不会写代码？「那你来这里干嘛？」',
  },
  {
    id: 'BM_10',
    name: '北极星指标',
    hook: 'onSettle',
    payload: { type: 'p1Bonus', value: 0.1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: 'P1 启动位 +10%',
    flavor: '全公司只看一个核心指标。然后这个指标拆成 20 个二级指标，二级拆成 80 个三级。每个团队抱着自己的星，互不相干。',
  },
  {
    id: 'BM_24',
    name: '销售文化',
    hook: 'onSettle',
    payload: { type: 'deptBonus', dept: 'S', value: 0.15 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: 'S 部门 +15%',
    flavor: '做销售不丢人。Top sales 年薪 200 万，技术大牛 80 万。「这就是市场。」',
  },
  {
    id: 'BM_25',
    name: '运营驱动',
    hook: 'onSettle',
    payload: { type: 'deptBonus', dept: 'O', value: 0.15 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: 'O 部门 +15%',
    flavor: '运营的天职是兜底。研发提需求，产品改需求，运营 24 小时盯线上。',
  },

  // ---- Rare (4) ----
  {
    "id": "BM_07",
    "name": "本地部署Deapseak",
    "hook": "onSettle",
    "payload": {
      "type": "srvApDiscount",
      "value": 1
    },
    "rarity": "rare",
    "unlockLevel": 1,
    "cost": 13,
    "description": "服务卡 AP -1",
    "flavor": "“给你一个最直接、不绕弯子的答案：”"
  },
  {
    id: 'BM_09',
    name: 'All-in 增长',
    hook: 'onSettle',
    payload: { type: 'p5Bonus', value: 0.2 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: 'P5 收割位 ×1.5 → ×1.7',
    flavor: 'ALL IN AI。ALL IN 元宇宙。ALL IN 大模型。ALL IN 出海。明年再 ALL IN 一个新方向。',
  },
  {
    id: 'BM_26',
    name: '飞轮效应',
    hook: 'onSettle',
    payload: { type: 'sameDeptAdjBonus', value: 0.2 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '同部门相邻 +20%',
    flavor: '某电商大佬说的飞轮，一开始转得慢，转起来谁都拦不住。可惜大部分公司还在推飞轮的第一圈。',
  },
  {
    id: 'BM_27',
    name: '产品经理至上',
    hook: 'onSettle',
    payload: { type: 'p1Bonus', value: 0.2 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: 'P1 启动位 +20%',
    flavor: '"某果厂教主说过..." "设计学教父说过..." "某顶级产品经理说过..."。然后产品上线被骂烂。',
  },

  // ---- Elite (4) ----
  {
    id: 'BM_28',
    name: '颠覆式创新 2.0',
    hook: 'onSettle',
    payload: { type: 'p5Bonus', value: 0.4 },
    rarity: 'elite',
    unlockLevel: 4,
    cost: 18,
    description: 'P5 收割位 ×1.5 → ×1.9',
    flavor: '管理学教科书说要从低端市场开始颠覆。我们说要从老板感兴趣的市场开始。',
  },
  {
    "id": "BM_29",
    "name": "现金牛牛矩阵",
    "hook": "onSettle",
    "payload": {
      "type": "sameDeptAdjBonus",
      "value": 0.3
    },
    "rarity": "elite",
    "unlockLevel": 4,
    "cost": 18,
    "description": "同部门相邻 +30%",
    "flavor": "没钱用BCG，用个他们的矩阵平替下～"
  },
  {
    id: 'BM_30',
    name: '政委巡查',
    hook: 'onSettle',
    payload: { type: 'deptBonus', dept: 'S', value: 0.3 },
    rarity: 'elite',
    unlockLevel: 4,
    cost: 18,
    description: 'S 部门 +30%',
    flavor: '组里有个"政委"，不写代码不做产品，但每周找你"谈话"两小时。谈完你就明白了。',
  },
  {
    id: 'BM_31',
    name: '永远微笑制',
    hook: 'onSettle',
    payload: { type: 'deptBonus', dept: 'O', value: 0.3 },
    rarity: 'elite',
    unlockLevel: 4,
    cost: 18,
    description: 'O 部门 +30%',
    flavor: '客户不是上帝，客户是体验。体验差了，就是你的问题。哪怕客户骂的是产品，那也是你的问题。',
  },

  // ---- Epic (1) ----
  {
    id: 'BM_32',
    name: '20% 副业制',
    hook: 'onSettle',
    payload: { type: 'deptBonus', dept: 'R', value: 0.4 },
    rarity: 'epic',
    unlockLevel: 6,
    cost: 24,
    description: 'R 部门 +40%',
    flavor: '每周可以花 20% 时间做自己想做的项目，剩下 80% 时间想该做什么。20% 项目里大部分变成了独立产品，少部分变成了"已关闭"。',
  },

  // ---- Legendary (1) ----
  {
    id: 'BM_33',
    name: '持有到老',
    hook: 'onSettle',
    payload: { type: 'p1Bonus', value: 0.3 },
    rarity: 'legendary',
    unlockLevel: 7,
    cost: 30,
    description: 'P1 启动位 +30%',
    flavor: '我们的持有期是永远，除非这家公司倒了，或者我活够了 100 岁。先到先得。',
  },

  // ============================================================================
  // onCharge · 一次性充能 (10 张)
  // ============================================================================

  // ---- Common (4) ----
  {
    id: 'BM_12',
    name: 'ESG 报告',
    hook: 'onCharge',
    payload: { type: 'levelEndBudgetBonus', value: 0.1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '关末战略预算 +10%',
    flavor: '把每个动作都包装成 Environmental, Social, Governance。投资人爱看 ESG，员工只能加班写报告。',
  },
  {
    id: 'BM_34',
    name: '券商进场',
    hook: 'onCharge',
    payload: { type: 'levelEndBudgetBonus', value: 0.15 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '关末战略预算 +15%',
    flavor: '讲故事比写代码重要。讲一个让承销商半夜睡不着、第二天连夜递招股书的故事。',
  },
  {
    id: 'BM_35',
    name: 'PR 公关战',
    hook: 'onCharge',
    payload: { type: 'levelEndBudgetBonus', value: 0.1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '关末战略预算 +10%',
    flavor: '今天上头条，明天上调查，后天上和解协议，下周继续上头条。流量就是价值。',
  },
  {
    id: 'BM_36',
    name: '使命愿景价值观',
    hook: 'onCharge',
    payload: { type: 'levelEndBudgetBonus', value: 0.1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '关末战略预算 +10%',
    flavor: '墙上贴着「让世界更美好」，工位贴着「客户第一」，会议室贴着「拥抱变化」。然后开会讨论的还是怎么裁员省钱。柯林斯听了直摇头。',
  },

  // ---- Rare (3) ----
  {
    id: 'BM_13',
    name: '反脆弱',
    hook: 'onCharge',
    payload: { type: 'waiveMaintenance' },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '每关 1 次免维持费',
    flavor: '《黑天鹅》作者讲的反脆弱：不光要抗风险，要从风险中获益。我们目前只学会了抗。',
  },
  {
    id: 'BM_37',
    name: 'All Hands 大会',
    hook: 'onCharge',
    payload: { type: 'waiveMaintenance' },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '每关 1 次免维持费',
    flavor: 'All Hands Q&A 是企业文化的核心。除非问到敏感问题，那叫「下个问题」。',
  },
  {
    id: 'BM_38',
    name: '延链补链强链',
    hook: 'onCharge',
    payload: { type: 'levelEndBudgetBonus', value: 0.25 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '关末战略预算 +25%',
    flavor: '上游延，下游补，中游强。延到了原材料，补到了渠道，强完发现：链上所有的钱都是自己花的。波特的价值链是这么用的？',
  },

  // ---- Elite (1) ----
  {
    id: 'BM_39',
    name: 'PPT 战略顾问',
    hook: 'onCharge',
    payload: { type: 'levelEndBudgetBonus', value: 0.3 },
    rarity: 'elite',
    unlockLevel: 4,
    cost: 18,
    description: '关末战略预算 +30%',
    flavor: '他们告诉你应该做什么，做完了再告诉你为什么没做好，最后告诉你下一步应该怎么做。账单 800 万，PPT 300 页。',
  },

  // ---- Epic (2) ----
  {
    id: 'BM_11',
    name: '颠覆式创新',
    hook: 'onCharge',
    payload: { type: 'reuseLine' },
    rarity: 'epic',
    unlockLevel: 6,
    cost: 24,
    description: '每关 1 次免冷却复用产线',
    flavor: '管理学教科书 1997 年提出，30 年来每个 CEO 都说自己在颠覆。真正颠覆的，10 个里有 1 个。',
  },
  {
    id: 'BM_40',
    name: '四宫格战略',
    hook: 'onCharge',
    payload: { type: 'reuseLine' },
    rarity: 'epic',
    unlockLevel: 6,
    cost: 24,
    description: '每关 1 次免冷却复用产线',
    flavor: '明星、奶牛、问号、瘦狗——把所有业务分成四类，然后什么也不做。咨询界的祖传 PPT。',
  },
]

/**
 * 卡包定义 (6 类，poolType 配合 engine.js 解析为具体卡池)
 */
export const PACK_DEFINITIONS = [
  {
    id: 'PACK_HEADHUNTER',
    name: '猎头礼包',
    icon: '👤',
    cost: 4,
    pickN: 1,
    fromN: 3,
    poolType: 'employee_common',
    description: '3 张普通员工卡选 1',
  },
  {
    id: 'PACK_ELITE',
    name: '精英礼包',
    icon: '⭐',
    cost: 8,
    pickN: 1,
    fromN: 3,
    poolType: 'employee_elite',
    description: '3 张精英员工卡选 1',
  },
  {
    id: 'PACK_SERVICE',
    name: '服务礼包',
    icon: '🛠️',
    cost: 5,
    pickN: 1,
    fromN: 3,
    poolType: 'service',
    description: '3 张服务卡选 1',
  },
  {
    id: 'PACK_FUNCTION',
    name: '功能礼包',
    icon: '📦',
    cost: 5,
    pickN: 1,
    fromN: 3,
    poolType: 'function',
    description: '3 张功能卡选 1',
  },
  {
    id: 'PACK_INSIGHT',
    name: '商业洞察',
    icon: '💡',
    cost: 7,
    pickN: 1,
    fromN: 3,
    poolType: 'business_model',
    description: '3 张商业模式选 1',
  },
  {
    id: 'PACK_MYSTERY',
    name: '神秘礼包',
    icon: '🎁',
    cost: 10,
    pickN: 1,
    fromN: 3,
    poolType: 'mystery',
    description: '跨稀有度，10% 出传奇',
  },
]

/**
 * 升职稀有度路径
 */
export const UPGRADE_PATHS = {
  common: { next: 'rare', cost: 10 },
  rare: { next: 'elite', cost: 15 },
  elite: { next: 'epic', cost: 20 },
  epic: null,
  legendary: null,
}

/**
 * 升职 ② 词缀附加池
 */
export const AFFIX_POOL = [
  { id: 'AFF_RIGHT_10', label: '→ 右邻 +10%', effects: ['RIGHT: +10%'] },
  { id: 'AFF_LEFT_10', label: '← 左邻 +10%', effects: ['LEFT: +10%'] },
  { id: 'AFF_BOTH_5', label: '↔ 双向 +5%', effects: ['BOTH: +5%'] },
  { id: 'AFF_SELF_8', label: '⚡ 自身 +8%', effects: ['SELF: +8%'] },
  { id: 'AFF_P5_20', label: '🎯 P5 +20%', effects: ['SELF_IF_P5: +20%'] },
  { id: 'AFF_COST_DOWN', label: '💰 维持费 -1', effects: ['MAINT: -1'] },
]

/**
 * 董事访谈随机事件 (5 个首版原型)
 */
export const BOARD_EVENTS = [
  {
    id: 'EV_BM_01',
    title: '核心员工被挖',
    flavor: '某竞品猎头以高出 50% 的薪资来挖你最强的研发主管。HR 把决策权交给了董事会：',
    options: [
      { id: 'A', label: '留人 (−💰8)', cost: 8, effect: { type: 'noop' }, result: '✓ 留住了王牌研发，士气稳定' },
      { id: 'B', label: '放走', effect: { type: 'removeBudgetBonus', value: 4 }, result: '失去一员大将，但收到 4 💰 补偿' },
      { id: 'C', label: '反挖对方 (−💰12)', cost: 12, effect: { type: 'recruitLegendary', dept: 'R', count: 1 }, result: '🔥 反挖成功！下关获得 1 张 R 部门传奇候选' },
    ],
  },
  {
    id: 'EV_BM_02',
    title: '投资人施压',
    flavor: '投资人在董事会上拍桌子要求下一季度立刻见效，扬言不达标就换 CEO：',
    options: [
      { id: 'A', label: '妥协 (下关目标 +10%)', effect: { type: 'increaseNextTarget', value: 0.1 }, result: '✓ 投资人满意离场' },
      { id: 'B', label: '顶住 (−💰5)', cost: 5, effect: { type: 'noop' }, result: '强硬态度让你保住了战略自主权' },
      { id: 'C', label: '反手画饼 (+💰3，下关首月手牌 -1)', effect: { type: 'budgetGainNextMonthPenalty', budget: 3 }, result: '✓ 用愿景换到 3 💰，但代价是下关首月手牌 -1' },
    ],
  },
  {
    id: 'EV_BM_03',
    title: '行业大会',
    flavor: '一年一度的行业大会即将召开，派哪个部门去最划算？',
    options: [
      { id: 'A', label: '派 R 团队', effect: { type: 'unlockEpic', dept: 'R' }, result: '✓ R 部门人脉打开，下关招聘池新增 1 张 R epic' },
      { id: 'B', label: '派 S 团队', effect: { type: 'unlockEpic', dept: 'S' }, result: '✓ S 部门拓展客户，下关招聘池新增 1 张 S epic' },
      { id: 'C', label: '派 O 团队', effect: { type: 'unlockEpic', dept: 'O' }, result: '✓ O 部门优化流程，下关招聘池新增 1 张 O epic' },
    ],
  },
  {
    id: 'EV_BM_04',
    title: '黑天鹅',
    flavor: '行业突发利好/利空各 50% 概率，赌不赌？',
    options: [
      { id: 'A', label: '顺势抄底', effect: { type: 'gamble', win: 10, lose: -5 }, result: '已写入顶栏' },
      { id: 'B', label: '谨慎观望', effect: { type: 'noop' }, result: '✓ 选择按兵不动' },
    ],
  },
  {
    id: 'EV_BM_05',
    title: '行业并购',
    flavor: '一家小型公司寻求被并购，吞下它能扩大商业模式上限：',
    options: [
      { id: 'A', label: '吞并 (−💰15，永久 +1 商业模式槽位)', cost: 15, effect: { type: 'increaseBmSlot' }, result: '✓ 并购完成，商业模式上限 +1' },
      { id: 'B', label: '拒绝 (+💰3)', effect: { type: 'budgetGain', value: 3 }, result: '保持精简，获得 3 💰 顾问费' },
      { id: 'C', label: '观望', effect: { type: 'noop' }, result: '✓ 没有动作' },
    ],
  },
]

export const STARTER_HAND = [
  ['EMP_R_01', 2],
  ['EMP_S_01', 2],
  ['EMP_O_01', 1],
  ['EMP_R_02', 1],
  ['FUN_01', 1],
]

export const STARTER_DECK = [
  ['EMP_R_01', 2],
  ['EMP_S_01', 2],
  ['EMP_O_01', 2],
  ['EMP_R_02', 1],
  ['EMP_S_02', 1],
  ['EMP_O_02', 2],
  ['FUN_02', 1],
  ['FUN_03', 1],
  ['FUN_04', 1],
  ['FUN_01', 1],
  ['SRV_02', 1],
]

export function getCardTemplate(id) {
  const template = CARD_TEMPLATES.find((card) => card.id === id)
  if (!template) {
    throw new Error(`Unknown card template: ${id}`)
  }
  return template
}

export function expandDeck(list) {
  return list.flatMap(([id, count]) => Array.from({ length: count }, () => id))
}

export function findStageByValuation(v) {
  let current = STAGES[0]
  for (const s of STAGES) {
    if (v >= s.threshold) {
      current = s
    }
  }
  return current
}

export function getCardBurn(card) {
  return card.baseBurn ?? RARITY_TABLE[card.rarity]?.baseBurn ?? 0
}

export function getCardExtraBurn(card) {
  return card.extraBurn ?? RARITY_TABLE[card.rarity]?.extraBurn ?? 0
}

export function getBMMonthlyCost(bm) {
  return bm.monthlyCost ?? RARITY_TABLE[bm.rarity]?.bmMonthlyCost ?? 0
}

export function getCardAssetValue(card) {
  return card.assetValue ?? RARITY_TABLE[card.rarity]?.assetValue ?? 0
}

export function getBMAssetValue(bm) {
  return bm.assetValue ?? RARITY_TABLE[bm.rarity]?.bmAssetValue ?? 0
}

for (const bm of BUSINESS_MODELS) {
  const rarityInfo = RARITY_TABLE[bm.rarity] || RARITY_TABLE.common
  bm.monthlyCost = bm.monthlyCost ?? rarityInfo.bmMonthlyCost
  bm.assetValue = bm.assetValue ?? rarityInfo.bmAssetValue
}
