export const RARITY_LABELS = {
  common: '普通',
  rare: '稀有',
  elite: '精英',
  epic: '史诗',
  legendary: '传奇',
}

export const RARITY_VARIANCE = {
  common: 0.1,
  rare: 0.15,
  elite: 0.2,
  epic: 0.25,
  legendary: 0.3,
}

export const DEPT_META = {
  R: { label: '研发部', short: '研发', color: 'rd', icon: 'R' },
  S: { label: '销售部', short: '销售', color: 'sales', icon: 'S' },
  O: { label: '运营部', short: '运营', color: 'ops', icon: 'O' },
  NONE: { label: '通用', short: '通用', color: 'neutral', icon: '*' },
}

export const LEVELS = [
  { id: 1, milestone: 'A 轮融资', theme: '起步打 PMF', target: 1200, startCash: 45, startBudget: 60, maintenance: 8 },
  { id: 2, milestone: 'B 轮融资', theme: '规模化', target: 2100, startCash: 60, startBudget: 95, maintenance: 12 },
  { id: 3, milestone: 'C 轮融资', theme: '抢市场', target: 3800, startCash: 80, startBudget: 150, maintenance: 18 },
]

export const EVENTS = [
  {
    id: 'angel-capital',
    name: '天使融资到账',
    tone: '增益',
    description: '投资人提前打款，运营窗口更宽。',
    effectLines: ['本月现金 +¥10', '本月招聘市场 +1'],
    cashDelta: 10,
    recruitExtra: 1,
    incomeMultiplier: 1,
    maintenanceMultiplier: 1,
  },
  {
    id: 'customer-consulting',
    name: '客户咨询',
    tone: '增益',
    description: '一批高意向客户主动找上门。',
    effectLines: ['本月产线收入 +15%', '销售相邻更容易放大'],
    cashDelta: 0,
    recruitExtra: 0,
    incomeMultiplier: 1.15,
    maintenanceMultiplier: 1,
  },
  {
    id: 'hiring-season',
    name: '招聘旺季',
    tone: '机会',
    description: '候选人质量和数量同步上升。',
    effectLines: ['招聘市场 +2', '战略预算不变'],
    cashDelta: 0,
    recruitExtra: 2,
    incomeMultiplier: 1,
    maintenanceMultiplier: 1,
  },
  {
    id: 'team-conflict',
    name: '团队冲突',
    tone: '风险',
    description: '沟通成本升高，管理资源被消耗。',
    effectLines: ['本月 AP 上限 -2', '产线仍可正常结算'],
    cashDelta: 0,
    apDelta: -2,
    recruitExtra: 0,
    incomeMultiplier: 1,
    maintenanceMultiplier: 1,
  },
  {
    id: 'industry-tailwind',
    name: '行业利好',
    tone: '增益',
    description: '市场窗口打开，所有收入被放大。',
    effectLines: ['本月 ¥ 收入 +20%'],
    cashDelta: 0,
    recruitExtra: 0,
    incomeMultiplier: 1.2,
    maintenanceMultiplier: 1,
  },
  {
    id: 'cash-crunch',
    name: '现金流危机',
    tone: '风险',
    description: '供应商账期收紧，维持费压力上升。',
    effectLines: ['本月维持费 x2', '律师/外包可免除'],
    cashDelta: 0,
    recruitExtra: 0,
    incomeMultiplier: 1,
    maintenanceMultiplier: 2,
  },
]

export const SMALL_AFFIXES = [
  { id: 'AFF_S_01', name: '加班狂', effects: ['BASE_OUTPUT: +30%'] },
  { id: 'AFF_S_02', name: '性价比', effects: ['COST: -40%'] },
  { id: 'AFF_S_03', name: '资深', effects: ['COST: +50%', 'BASE_OUTPUT: +25%'] },
  { id: 'AFF_S_05', name: '团魂', effects: ['SAME_DEPT_ADJ_EXTRA: +10%'] },
  { id: 'AFF_S_07', name: '完美主义', effects: ['SELF_IF_P3: +25%'] },
  { id: 'AFF_S_08', name: '收割者', effects: ['SELF_IF_P5: +30%'] },
  { id: 'AFF_S_10', name: '学霸', effects: ['SELF_IF_ADJ_FUN: +20%'] },
]

export const LARGE_AFFIXES = [
  { id: 'AFF_L_02', name: '双倍工作', effects: ['NO_COOLDOWN'] },
  { id: 'AFF_L_05', name: '化学反应', effects: ['SAME_DEPT_ADJ_EXTRA: +25%'] },
  { id: 'AFF_L_08', name: '大佬光环', effects: ['LINE_ALL: +15%'] },
  { id: 'AFF_L_10', name: '一颗螺丝钉', effects: ['LINE_ALL: +12%'] },
  { id: 'AFF_L_11', name: '跨界鬼才', effects: ['IF_ALL_THREE_DEPT_IN_LINE: LINE_ALL: x1.5'] },
]

export const CARD_TEMPLATES = [
  {
    id: 'EMP_R_01',
    name: '研发专员',
    type: 'emp',
    dept: 'R',
    tier: '专员',
    rarity: 'common',
    unlockLevel: 1,
    ap: 1,
    costSpec: '5 ±10%',
    baseOutputSpec: '20 ±10%',
    effects: ['RIGHT: +10% ±10%'],
    flavor: '刚毕业的小伙子，加班贼狠',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_02',
    name: '研发经理',
    type: 'emp',
    dept: 'R',
    tier: '经理',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '11 ±10%',
    baseOutputSpec: '45 ±10%',
    effects: ['RIGHT: +25% ±10%'],
    flavor: '技术骨干升上来的，能写代码也能带人',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_03',
    name: '研发总监',
    type: 'emp',
    dept: 'R',
    tier: '总监',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 4,
    costSpec: '22 ±15%',
    baseOutputSpec: '85 ±15%',
    effects: ['RIGHT: +40% ±15%', 'SELF_IF_P1: +20%'],
    flavor: '技术线最高决策者，路线图全靠他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_04',
    name: '算法专家',
    type: 'emp',
    dept: 'R',
    tier: '专员',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 2,
    costSpec: '15 ±15%',
    baseOutputSpec: '35 ±15%',
    effects: ['SELF_IF_RIGHT_FUN: x1.5', 'RIGHT: +15% ±15%'],
    flavor: '懂数据、懂模型，但不太会说话',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_05',
    name: '全栈工程师',
    type: 'emp',
    dept: 'R',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 3,
    costSpec: '17 ±15%',
    baseOutputSpec: '55 ±15%',
    effects: ['BOTH: +15% ±15%'],
    flavor: '一个人顶三个用，但跳槽风险大',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_06',
    name: '架构师',
    type: 'emp',
    dept: 'R',
    tier: '总监',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 4,
    costSpec: '25 ±15%',
    baseOutputSpec: '75 ±15%',
    effects: ['SAME_DEPT_ADJ: +30%', 'RIGHT: +20% ±15%'],
    flavor: '图画得比代码多，但你不能没有他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_07',
    name: '技术 VP',
    type: 'emp',
    dept: 'R',
    tier: 'VP',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 5,
    costSpec: '35 ±20%',
    baseOutputSpec: '120 ±20%',
    effects: ['LINE_ALL_R: +25%', 'RIGHT: +30% ±20%'],
    flavor: '技术线副总裁，话不多但说话顶用',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_08',
    name: '首席科学家',
    type: 'emp',
    dept: 'R',
    tier: 'VP',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 5,
    costSpec: '45 ±25%',
    baseOutputSpec: '140 ±25%',
    effects: ['SELF_IF_P3: BOTH: +40%', 'MONTH_STAR_RATE: +5%'],
    flavor: '顶着 PhD 学位的明星，估值看脸的关键',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_09',
    name: '极客实习生',
    type: 'emp',
    dept: 'R',
    tier: '专员',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 2,
    costSpec: '10 ±20%',
    baseOutputSpec: '38 ±20%',
    effects: ['RIGHT: +30% ±20%', 'TRIGGER: SELF_IF_LEFT_DEPT_R: SELF: x2'],
    flavor: '成本极低产出极高，但容易被挖',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_01',
    name: '销售专员',
    type: 'emp',
    dept: 'S',
    tier: '专员',
    rarity: 'common',
    unlockLevel: 1,
    ap: 1,
    costSpec: '5 ±10%',
    baseOutputSpec: '20 ±10%',
    effects: ['LEFT: +10% ±10%'],
    flavor: '电话打到嗓子哑，提成是动力',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_02',
    name: '销售经理',
    type: 'emp',
    dept: 'S',
    tier: '经理',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '11 ±10%',
    baseOutputSpec: '45 ±10%',
    effects: ['LEFT: +20% ±10%'],
    flavor: '带一支小队，月度冠军常客',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_03',
    name: '销售总监',
    type: 'emp',
    dept: 'S',
    tier: '总监',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 4,
    costSpec: '22 ±15%',
    baseOutputSpec: '85 ±15%',
    effects: ['LEFT: +35% ±15%', 'SELF_IF_P5: x1.5'],
    flavor: '客户全在他手机里，公司离不开他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_04',
    name: '大客户经理',
    type: 'emp',
    dept: 'S',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 3,
    costSpec: '17 ±15%',
    baseOutputSpec: '55 ±15%',
    effects: ['LEFT: +15% ±15%', 'SELF_IF_LEFT_DEPT_R: x1.4'],
    flavor: '专啃硬骨头，订单一签就是几百万',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_05',
    name: 'BD 专员',
    type: 'emp',
    dept: 'S',
    tier: '专员',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 2,
    costSpec: '13 ±15%',
    baseOutputSpec: '30 ±15%',
    effects: ['LEFT: +12% ±15%', 'MONTH_BONUS: +¥3'],
    flavor: 'BD 全靠人脉，吃饭喝酒签合作',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_06',
    name: '电商运营',
    type: 'emp',
    dept: 'S',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '18 ±15%',
    baseOutputSpec: '50 ±15%',
    effects: ['BOTH: +12% ±15%', 'TRIGGER: SELF_IF_LINE_HAS_FUN: x1.3'],
    flavor: 'GMV 主义者，永远在 ABtest',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_07',
    name: '销售 VP',
    type: 'emp',
    dept: 'S',
    tier: 'VP',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 5,
    costSpec: '35 ±20%',
    baseOutputSpec: '120 ±20%',
    effects: ['LINE_ALL_S: +25%', 'LEFT: +30% ±20%'],
    flavor: '销售一把手，KPI 拍板靠他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_08',
    name: '销售之神',
    type: 'emp',
    dept: 'S',
    tier: 'VP',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 5,
    costSpec: '45 ±25%',
    baseOutputSpec: '140 ±25%',
    effects: ['SELF_IF_P5: SELF: x2.5', 'LEFT: +30% ±25%'],
    flavor: '传说级销售，开口就是大单',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_09',
    name: '客户成功',
    type: 'emp',
    dept: 'S',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '17 ±15%',
    baseOutputSpec: '50 ±15%',
    effects: ['LEFT: +18% ±15%', 'SAME_DEPT_ADJ: +¥2'],
    flavor: '续约率王者，老客户都认他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_01',
    name: '运营专员',
    type: 'emp',
    dept: 'O',
    tier: '专员',
    rarity: 'common',
    unlockLevel: 1,
    ap: 1,
    costSpec: '5 ±10%',
    baseOutputSpec: '22 ±10%',
    effects: ['SAME_DEPT_ADJ: +¥1'],
    flavor: 'Excel 大师，表格能开花',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_02',
    name: '运营经理',
    type: 'emp',
    dept: 'O',
    tier: '经理',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '11 ±10%',
    baseOutputSpec: '48 ±10%',
    effects: ['SAME_DEPT_ADJ: +¥2', 'BOTH: +10% ±10%'],
    flavor: '流程优化狂魔，省钱的能手',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_03',
    name: '运营总监',
    type: 'emp',
    dept: 'O',
    tier: '总监',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 4,
    costSpec: '22 ±15%',
    baseOutputSpec: '85 ±15%',
    effects: ['SAME_DEPT_ADJ: +¥3', 'SELF_IF_P3: BOTH: +25%'],
    flavor: '公司大管家，老板甩手掌柜全靠他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_04',
    name: 'HR 经理',
    type: 'emp',
    dept: 'O',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 3,
    costSpec: '16 ±15%',
    baseOutputSpec: '45 ±15%',
    effects: ['LINE_ALL: +8% ±15%', 'MONTH_BONUS: +¥2'],
    flavor: '招聘留人都是他，但绩效面谈让人怕',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_05',
    name: '财务经理',
    type: 'emp',
    dept: 'O',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 3,
    costSpec: '18 ±15%',
    baseOutputSpec: '40 ±15%',
    effects: ['MONTH_BONUS: +¥5', 'BOTH: +8% ±15%'],
    flavor: '管钱袋子的人，老板真正的朋友',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_06',
    name: '项目经理 PM',
    type: 'emp',
    dept: 'O',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '17 ±15%',
    baseOutputSpec: '50 ±15%',
    effects: ['BOTH: +20% ±15%', 'TRIGGER: SELF_IF_LEFT_DEPT_R_AND_RIGHT_DEPT_S: SELF: x1.5'],
    flavor: '甘特图战神，跨部门翻译机',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_07',
    name: '运营 VP / COO',
    type: 'emp',
    dept: 'O',
    tier: 'VP',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 5,
    costSpec: '38 ±20%',
    baseOutputSpec: '115 ±20%',
    effects: ['LINE_ALL: +15%', 'MONTH_BONUS: +¥10'],
    flavor: '首席运营官，公司日常运转的中枢',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_08',
    name: '行政总管',
    type: 'emp',
    dept: 'O',
    tier: '总监',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 4,
    costSpec: '20 ±15%',
    baseOutputSpec: '70 ±15%',
    effects: ['MONTH_NO_MAINTAIN', 'BOTH: +10% ±15%'],
    flavor: '省下的就是赚到的',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_09',
    name: '数据分析师',
    type: 'emp',
    dept: 'O',
    tier: '专员',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 2,
    costSpec: '13 ±15%',
    baseOutputSpec: '32 ±15%',
    effects: ['BOTH: +18% ±15%', 'TRIGGER: SELF_IF_ADJ_FUN: SELF: x1.4'],
    flavor: 'SQL 写得比情书还多，数字驱动决策',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_01',
    name: '市场调研',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '7 ±10%',
    baseOutputSpec: '0',
    effects: ['BOTH: +25% ±10%'],
    flavor: '了解客户才能搞定客户',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'FUN_02',
    name: '产品冲刺',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 1,
    ap: 3,
    costSpec: '9 ±10%',
    baseOutputSpec: '0',
    effects: ['ADJ_R: x2 ±10%'],
    flavor: '全部门拼一把，发版日就是验货日',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'FUN_03',
    name: '团队建设',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '8 ±10%',
    baseOutputSpec: '0',
    effects: ['LINE_ALL: +¥15 ±10%'],
    flavor: '团建不是吃饭，是凝聚力投资',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'FUN_04',
    name: '产品推广',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 1,
    ap: 3,
    costSpec: '9 ±10%',
    baseOutputSpec: '0',
    effects: ['ADJ_S: x2 ±10%'],
    flavor: '酒香也怕巷子深，推广要趁早',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'FUN_05',
    name: '数据分析',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 2,
    ap: 2,
    costSpec: '7 ±10%',
    baseOutputSpec: '0',
    effects: ['LEFT: +30% ±10%'],
    flavor: '用数据说话，向上汇报必备',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_06',
    name: '流程优化',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 2,
    ap: 2,
    costSpec: '7 ±10%',
    baseOutputSpec: '0',
    effects: ['RIGHT: +30% ±10%'],
    flavor: '把繁琐变简单，把简单变高效',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_07',
    name: '跨部门协作',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '13 ±15%',
    baseOutputSpec: '0',
    effects: ['TRIGGER: LEFT_DEPT != RIGHT_DEPT: BOTH: +40% ±15%'],
    flavor: '墙太厚要敲掉，孤岛太多要修桥',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_08',
    name: 'OKR 制定',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '13 ±15%',
    baseOutputSpec: '0',
    effects: ['LINE_ALL: +15% ±15%', 'MONTH_STAR_RATE: +3%'],
    flavor: '目标对齐了，效率才有意义',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_09',
    name: '加班动员',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 2,
    ap: 2,
    costSpec: '7 ±10%',
    baseOutputSpec: '0',
    effects: ['LINE_ALL: +20% ±10%'],
    flavor: '冲一波，但下个月别怪我',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_10',
    name: '品牌建设',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '15 ±15%',
    baseOutputSpec: '0',
    effects: ['BOTH: +20% ±15%', 'MONTH_STAR_RATE: +8%'],
    flavor: '品牌即资产，长期主义的体现',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_11',
    name: '用户运营活动',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '14 ±15%',
    baseOutputSpec: '0',
    effects: ['ADJ_S: +50% ±15%', 'MONTH_BONUS: +¥10'],
    flavor: '拉新促活，私域引流的标配',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_12',
    name: '技术债务清理',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'rare',
    unlockLevel: 4,
    ap: 3,
    costSpec: '14 ±15%',
    baseOutputSpec: '0',
    effects: ['ADJ_R: +50% ±15%'],
    flavor: '前人欠的债，后人还，但还完爽',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_01',
    name: '律师事务所',
    type: 'srv',
    dept: 'NONE',
    tier: '基础',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '8 ±10%',
    baseOutputSpec: '0',
    effects: ['MONTH_NO_MAINTAIN'],
    flavor: '合同审查 + 风险规避，省钱的法宝',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'SRV_02',
    name: '税务筹划',
    type: 'srv',
    dept: 'NONE',
    tier: '基础',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '8 ±10%',
    baseOutputSpec: '0',
    effects: ['MONTH_STAR_RATE: +5%'],
    flavor: '合法节税是企业必修课',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_03',
    name: '外部咨询',
    type: 'srv',
    dept: 'NONE',
    tier: '进阶',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 4,
    costSpec: '19 ±15%',
    baseOutputSpec: '0',
    effects: ['LINE_XMULT: x1.3 ±15%'],
    flavor: 'Mck.ey 一份报告，半年战略不愁',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_04',
    name: '融资顾问',
    type: 'srv',
    dept: 'NONE',
    tier: '进阶',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 3,
    costSpec: '15 ±15%',
    baseOutputSpec: '0',
    effects: ['MONTH_BONUS: +¥15 ±15%', 'MONTH_STAR_RATE: +3%'],
    flavor: '对接 VC、修 BP，专业的人做专业的事',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_05',
    name: '管理咨询',
    type: 'srv',
    dept: 'NONE',
    tier: '顶级',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 5,
    costSpec: '32 ±20%',
    baseOutputSpec: '0',
    effects: ['MONTH_AP: +5'],
    flavor: '组织架构 + 流程再造的大手术',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_06',
    name: '战略顾问',
    type: 'srv',
    dept: 'NONE',
    tier: '顶级',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 5,
    costSpec: '32 ±20%',
    baseOutputSpec: '0',
    effects: ['LINE_ALL: +30% ±20%'],
    flavor: '看远一些，走稳一些',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_07',
    name: 'PR 公关',
    type: 'srv',
    dept: 'NONE',
    tier: '进阶',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '15 ±15%',
    baseOutputSpec: '0',
    effects: ['MONTH_STAR_RATE: +10%'],
    flavor: '口碑、热度、声誉，都是真金白银',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_08',
    name: 'HR 外包',
    type: 'srv',
    dept: 'NONE',
    tier: '基础',
    rarity: 'common',
    unlockLevel: 2,
    ap: 2,
    costSpec: '9 ±10%',
    baseOutputSpec: '0',
    effects: ['MONTH_NO_MAINTAIN', 'BOTH: +5% ±10%'],
    flavor: '把杂活外包出去，专注主业',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_09',
    name: '投行顾问',
    type: 'srv',
    dept: 'NONE',
    tier: '顶级',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 5,
    costSpec: '40 ±25%',
    baseOutputSpec: '0',
    effects: ['MONTH_BONUS: +¥30 ±25%', 'MONTH_STAR_RATE: +15%'],
    flavor: '上市路上的必经合作伙伴',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_10',
    name: '法律团队',
    type: 'srv',
    dept: 'NONE',
    tier: '进阶',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '16 ±15%',
    baseOutputSpec: '0',
    effects: ['MONTH_NO_MAINTAIN', 'LINE_ALL: +10% ±15%'],
    flavor: '升级版律师，覆盖知识产权、并购',
    inStarterDeck: false,
    inRecruitPool: true,
  },
]

export const STARTER_HAND = [
  ['EMP_R_01', 2],
  ['EMP_S_01', 2],
  ['EMP_O_01', 1],
  ['EMP_R_02', 1],
  ['FUN_01', 1],
]

export const STARTER_DECK = [
  ['EMP_R_01', 2],
  ['EMP_S_01', 2],
  ['EMP_O_01', 2],
  ['EMP_R_02', 1],
  ['EMP_S_02', 1],
  ['EMP_O_02', 2],
  ['FUN_02', 1],
  ['FUN_03', 1],
  ['FUN_04', 1],
  ['FUN_01', 1],
  ['SRV_02', 1],
]

export function getCardTemplate(id) {
  const template = CARD_TEMPLATES.find((card) => card.id === id)
  if (!template) {
    throw new Error(`Unknown card template: ${id}`)
  }
  return template
}

export function expandDeck(list) {
  return list.flatMap(([id, count]) => Array.from({ length: count }, () => id))
}
