export const RARITY_LABELS = {
  common: '普通',
  rare: '稀有',
  elite: '精英',
  epic: '史诗',
  legendary: '传奇',
}

export const POSITION_LABELS = {
  common: '专员',
  rare: '经理',
  elite: '总监',
  epic: 'VP',
  legendary: 'CXO',
}


export const RARITY_VARIANCE = {
  common: 0.1,
  rare: 0.15,
  elite: 0.2,
  epic: 0.25,
  legendary: 0.3,
}

export const DEPT_META = {
  R: { label: '研发部', short: '研发', color: 'rd', icon: 'R' },
  S: { label: '销售部', short: '销售', color: 'sales', icon: 'S' },
  O: { label: '运营部', short: '运营', color: 'ops', icon: 'O' },
  NONE: { label: '通用', short: '通用', color: 'neutral', icon: '*' },
}

export const PROFESSION_TRACKS = {
  scientist: {
    id: 'ai',
    label: 'AI / 研发赛道',
    coreDept: 'R',
    supportDept: 'O',
    genericWeight: 0.3,
    coreWeight: 0.5,
    supportWeight: 0.2,
  },
  sales: {
    id: 'growth',
    label: '增长 / 销售赛道',
    coreDept: 'S',
    supportDept: 'R',
    genericWeight: 0.3,
    coreWeight: 0.5,
    supportWeight: 0.2,
  },
  cxo: {
    id: 'ops',
    label: '运营 / 平台赛道',
    coreDept: 'O',
    supportDept: 'S',
    genericWeight: 0.3,
    coreWeight: 0.5,
    supportWeight: 0.2,
  },
}

export function getProfessionTrack(profession = 'scientist') {
  return PROFESSION_TRACKS[profession] ?? PROFESSION_TRACKS.scientist
}

/** @deprecated Use STAGES instead */
export const LEVELS = [
  { id: 1, milestone: 'A 轮融资', theme: '起步打 PMF', target: 1200, startCash: 45, startBudget: 60, maintenance: 8 },
  { id: 2, milestone: 'B 轮融资', theme: '规模化', target: 2100, startCash: 60, startBudget: 95, maintenance: 12 },
  { id: 3, milestone: 'C 轮融资', theme: '抢市场', target: 3800, startCash: 80, startBudget: 150, maintenance: 18 },
]

export const STAGES = [
  { id: 1, key: 'angel',   name: '天使轮', threshold: 0,     entryGrant: 30,   theme: '起步' },
  { id: 2, key: 'seed',    name: '种子轮', threshold: 900,   entryGrant: 70,   theme: '产品验证' },
  { id: 3, key: 'seriesA', name: 'A 轮',   threshold: 1800,  entryGrant: 140,  theme: '规模化' },
  { id: 4, key: 'seriesB', name: 'B 轮',   threshold: 3400,  entryGrant: 260,  theme: '增长' },
  { id: 5, key: 'seriesC', name: 'C 轮',   threshold: 6200,  entryGrant: 440,  theme: '扩张' },
  { id: 6, key: 'seriesD', name: 'D 轮',   threshold: 9800,  entryGrant: 700,  theme: '深耕' },
  { id: 7, key: 'ipo',     name: 'IPO',     threshold: 12500, entryGrant: 1050, theme: '上市' },
  { id: 8, key: 'giant',   name: '千亿',    threshold: 15500, entryGrant: 1500, theme: '巨头' },
  { id: 9, key: 'first',   name: '行业第一', threshold: 19000, entryGrant: 2200, theme: '终极' },
]

// 现金转化率（CCR · Cash Conversion Rate）
// 月利润 × CCR → 实际入账现金；其余作为"未变现的账面价值"（叙事用，不影响机制）
// 仅作用于正利润；负利润 100% 从 cash 扣减
export const CASH_CONVERSION_RATES = {
  1: 0.72, 2: 0.70, 3: 0.66,
  4: 0.62, 5: 0.58, 6: 0.53,
  7: 0.48, 8: 0.44, 9: 0.40,
}

export function getCashConversionRate(stageId, bmCcrBonus = 0) {
  const base = CASH_CONVERSION_RATES[stageId] ?? 0.7
  return Math.min(1.0, base + bmCcrBonus)
}

// 月度固定运营成本（每月末从 cash 扣减）
export function getMonthlyOperationCost(stageId) {
  const stage = Math.max(1, stageId ?? 1)
  return Math.round(14 + stage * stage * 1.6 + stage * 3)
}

// ============================================================================
// v4 卡牌新 schema：固定 L1 部门主轴 + 按稀有度随机功能池
// ============================================================================

/**
 * 部门 L1 主轴效果矩阵（按 tier × dept 索引）
 *  - R 部门: 抓牌（速度）—— 使用 DRAW_NEXT_MONTH 效果，由 engine.js 在 resolveMonth 应用
 *  - S 部门: 倍数（暴击）—— 使用现有 SELF/RIGHT/LINE_ALL 效果，由 computeLineOutput 应用
 *  - O 部门: AP（厚度）—— 使用现有 MONTH_AP 效果，由 getEffectiveApLimit 应用
 *  - 专员 (specialist) 层不带主轴，作为"流派砖块"靠堆数量赚 combo / 流派质变收益
 *  - 创始人 / 传奇 / 功能 / 服务卡走自己的 template.effects，不走此表
 */
export const DEPT_L1_EFFECTS = {
  R: {
    专员: [],
    经理: ['DRAW_NEXT_MONTH: +1'],
    总监: ['DRAW_NEXT_MONTH: +2'],
    VP:   ['DRAW_NEXT_MONTH: +2'],
    CXO:  ['DRAW_NEXT_MONTH: +3'],
  },
  S: {
    专员: [],
    经理: ['SELF: +15%'],
    总监: ['RIGHT: +20%'],
    VP:   ['LINE_ALL: +15%'],
    CXO:  ['LINE_ALL: +20%'],
  },
  O: {
    专员: [],
    经理: ['MONTH_AP: +1'],
    总监: ['MONTH_AP: +1'],
    VP:   ['MONTH_AP: +2'],
    CXO:  ['MONTH_AP: +2'],
  },
}

/**
 * 随机功能池：按 lv 分级
 *  - lv1 微小：5-15% 单点 buff，资源类小补
 *  - lv2 小：15-25% 单/双向 buff
 *  - lv3 中：25-35% 单/双向 / 同部门相邻
 *  - lv4 大：整线 / 部门线 buff
 * 已移除所有"永久 X"类（NO_COOLDOWN / WHILE_ACTIVE / EACH_MONTH 等）以保平衡
 */
export const RANDOM_FUNCTION_POOL = {
  lv1: [
    { id: 'F1_01', name: '完美主义', effects: ['SELF_IF_P3: +15%'] },
    { id: 'F1_02', name: '启动者',   effects: ['SELF_IF_P1: +15%'] },
    { id: 'F1_03', name: '收割者',   effects: ['SELF_IF_P5: +15%'] },
    { id: 'F1_04', name: '团魂',     effects: ['SAME_DEPT_ADJ: +5%'] },
    { id: 'F1_05', name: '学霸',     effects: ['SELF_IF_ADJ_FUN: +10%'] },
    { id: 'F1_06', name: '加班狂',   effects: ['SELF: +15%'] },
    { id: 'F1_07', name: '资金奶牛', effects: ['MONTH_BONUS: +¥3'] },
    { id: 'F1_08', name: '桥梁',     effects: ['DIFF_DEPT_ADJ_EXTRA: +8%'] },
    { id: 'F1_09', name: '微调',     effects: ['SELF: +10%'] },
    { id: 'F1_10', name: '调和',     effects: ['BOTH: +5%'] },
    { id: 'F1_R_01', name: '技术嗅觉', effects: ['DRAW_NEXT_MONTH: +1'] },
    { id: 'F1_S_01', name: '成交雷达', effects: ['MONTH_BONUS: +¥5'] },
    { id: 'F1_O_01', name: '流程手感', effects: ['MONTH_AP: +1'] },
    { id: 'F1_G_01', name: '风险垫片', effects: ['LINE_ALL: +6%'] },
  ],
  lv2: [
    { id: 'F2_01', name: '左援',     effects: ['LEFT: +15%'] },
    { id: 'F2_02', name: '右援',     effects: ['RIGHT: +15%'] },
    { id: 'F2_03', name: '双向调和', effects: ['BOTH: +10%'] },
    { id: 'F2_04', name: '完美主义+', effects: ['SELF_IF_P3: +30%'] },
    { id: 'F2_05', name: '收割者+', effects: ['SELF_IF_P5: +30%'] },
    { id: 'F2_06', name: '工具人',   effects: ['SELF_IF_ADJ_FUN: +20%'] },
    { id: 'F2_07', name: '小金库',   effects: ['MONTH_BONUS: +¥8'] },
    { id: 'F2_08', name: '加班狂+', effects: ['SELF: +25%'] },
    { id: 'F2_R_01', name: '技术资产化', effects: ['LINE_ALL_R: +12%'] },
    { id: 'F2_S_01', name: '渠道嗅觉', effects: ['LINE_ALL_S: +12%'] },
    { id: 'F2_O_01', name: '省钱本能', effects: ['MONTH_NO_MAINTAIN'] },
    { id: 'F2_G_01', name: '组合意识', effects: ['IF_ALL_THREE_DEPT_IN_LINE: x1.15'] },
  ],
  lv3: [
    { id: 'F3_01', name: '部门核心', effects: ['SAME_DEPT_ADJ: +25%'] },
    { id: 'F3_02', name: '产线增益', effects: ['LINE_ALL: +12%'] },
    { id: 'F3_03', name: '强力左援', effects: ['LEFT: +30%'] },
    { id: 'F3_04', name: '强力右援', effects: ['RIGHT: +30%'] },
    { id: 'F3_05', name: '化学反应', effects: ['SAME_DEPT_ADJ: +35%'] },
    { id: 'F3_06', name: '大佬光环', effects: ['LINE_ALL: +15%'] },
    { id: 'F3_R_01', name: '模型护城河', effects: ['LINE_ALL_R: +20%', 'MONTH_STAR_RATE: +4%'] },
    { id: 'F3_S_01', name: '品牌飞轮', effects: ['LINE_ALL_S: +20%', 'MONTH_BONUS: +¥10'] },
    { id: 'F3_O_01', name: '组织韧性', effects: ['LINE_ALL_O: +20%', 'MONTH_AP: +1'] },
  ],
  lv4: [
    { id: 'F4_01', name: '研发线领袖', effects: ['LINE_ALL_R: +25%'] },
    { id: 'F4_02', name: '销售线领袖', effects: ['LINE_ALL_S: +25%'] },
    { id: 'F4_03', name: '运营线领袖', effects: ['LINE_ALL_O: +25%'] },
    { id: 'F4_04', name: '现金奶牛',   effects: ['MONTH_BONUS: +¥20'] },
    { id: 'F4_05', name: '一颗螺丝钉', effects: ['LINE_ALL: +25%'] },
  ],
}

/**
 * 稀有度 → (随机功能数量, 可抽功能 lv 范围) 映射
 *  注意：与 plan §4.5 一致
 */
export const RARITY_RANDOM_SPEC = {
  common:    { fnCount: 0, lvRange: ['lv1'],    secondFnChance: 0.35 },
  rare:      { fnCount: 1, lvRange: ['lv1', 'lv2'], secondFnChance: 0 },
  elite:     { fnCount: 1, lvRange: ['lv1', 'lv2', 'lv3'], secondFnChance: 0.3 },
  epic:      { fnCount: 2, lvRange: ['lv2', 'lv3'], secondFnChance: 0 },
  legendary: { fnCount: 2, lvRange: ['lv2', 'lv3', 'lv4'], secondFnChance: 0.5 },
}

/**
 * 判断某员工卡是否走 v4 标准 schema（固定 L1 + 随机功能池）
 * 不走 schema 的：创始人 / 传奇 / 非员工卡，保留 template.effects 原样
 */
export function usesStandardEmpSchema(template) {
  if (template.type !== 'emp') return false
  if (template.tier === '创始人') return false
  if (template.rarity === 'legendary') return false
  if (!DEPT_L1_EFFECTS[template.dept]) return false
  return true
}

/**
 * 根据 dept + tier 取 L1 主轴效果数组
 */
export function getDeptL1Effects(dept, tier) {
  return DEPT_L1_EFFECTS[dept]?.[tier] ?? []
}

/**
 * 在功能池中按指定 lv 范围随机抽 1 个，排除已抽过的
 */
export function pickRandomFunction(lvRange, excludeIds = new Set(), rng = Math.random) {
  if (!lvRange?.length) return null
  const lv = lvRange[Math.floor(rng() * lvRange.length)]
  const pool = (RANDOM_FUNCTION_POOL[lv] ?? []).filter(f => !excludeIds.has(f.id))
  if (!pool.length) return null
  return pool[Math.floor(rng() * pool.length)]
}

/**
 * 按稀有度生成员工卡的随机功能列表
 */
export function rollRandomFunctions(rarity, rng = Math.random) {
  const spec = RARITY_RANDOM_SPEC[rarity] ?? RARITY_RANDOM_SPEC.common
  const results = []
  const used = new Set()
  if (spec.fnCount === 0 && spec.secondFnChance > 0) {
    if (rng() < spec.secondFnChance) {
      const fn = pickRandomFunction(spec.lvRange, used, rng)
      if (fn) results.push(fn)
    }
    return results
  }
  for (let i = 0; i < spec.fnCount; i++) {
    const fn = pickRandomFunction(spec.lvRange, used, rng)
    if (fn) { results.push(fn); used.add(fn.id) }
  }
  // secondFnChance: 抽完基础后还有一定概率多抽 1 个
  if (spec.secondFnChance > 0 && rng() < spec.secondFnChance) {
    const extra = pickRandomFunction(spec.lvRange, used, rng)
    if (extra) results.push(extra)
  }
  return results
}

export const RARITY_TABLE = {
  common:    { baseBurn: 3,  extraBurn: 2,  assetValue: 6,   bmMonthlyCost: 5,  bmAssetValue: 10  },
  rare:      { baseBurn: 6,  extraBurn: 4,  assetValue: 18,  bmMonthlyCost: 10, bmAssetValue: 32  },
  elite:     { baseBurn: 11, extraBurn: 8,  assetValue: 40,  bmMonthlyCost: 17, bmAssetValue: 65  },
  epic:      { baseBurn: 18, extraBurn: 13, assetValue: 75,  bmMonthlyCost: 28, bmAssetValue: 110 },
  legendary: { baseBurn: 32, extraBurn: 22, assetValue: 170, bmMonthlyCost: 46, bmAssetValue: 280 },
}

export const TIER_BURN_BONUS = {
  专员: 0,
  经理: 1,
  总监: 3,
  VP: 7,
  CXO: 12,
  创始人: 8,
}

export const FUNCTION_CARD_ACTIONS = {
  FUN_01: [
    { id: 'scan_market', label: '抽 4 选 2', description: '立刻抽 4 张，留下前 2 张，其余洗回牌堆', effect: { type: 'drawSelect', draw: 4, keep: 2 } },
    { id: 'pe_memo', label: 'PE 叙事 +12%（2 月）', description: '未来 2 个月估值叙事放大', effect: { type: 'peBuff', value: 0.12, months: 2 } },
  ],
  FUN_02: [
    { id: 'launch_demo', label: '技术发布会', description: '未来 2 个月 PE +18%，但现金 -80', cost: 80, effect: { type: 'peBuff', value: 0.18, months: 2 } },
    { id: 'delay_boss_ai', label: '开源烟雾弹', description: '未开战 boss 延后 3 个月；已开战则战期 +1 月', effect: { type: 'delayBoss', months: 3 } },
  ],
  FUN_03: [
    { id: 'war_room', label: '紧急董事会', description: '下个月强制召开一次董事会', effect: { type: 'emergencyBoard' } },
    { id: 'runway', label: '现金跑道', description: '花 ¥120，未来 2 个月 burn -20%', cost: 120, effect: { type: 'cashToRunway', months: 2, discount: 0.2 } },
  ],
  FUN_04: [
    { id: 'brand_blitz', label: '品牌闪击', description: '下月 boss 对手收入 -25%', effect: { type: 'rivalDebuff', months: 1, rivalIncomeMult: 0.75 } },
    { id: 'promo_pe', label: '增长故事 +15%（2 月）', description: '未来 2 个月 PE +15%', effect: { type: 'peBuff', value: 0.15, months: 2 } },
  ],
  FUN_05: [
    { id: 'data_room', label: '数据作战室', description: '抽 5 选 2，强化本季度决策', effect: { type: 'drawSelect', draw: 5, keep: 2 } },
    { id: 'boss_read', label: '对手画像', description: '下月 boss 技能屏蔽并收入 -10%', effect: { type: 'rivalDebuff', months: 1, rivalIncomeMult: 0.9, skillBlocked: true } },
  ],
  FUN_06: [
    { id: 'ops_sweep', label: '流程扫除', description: '未来 2 个月 burn -15%', effect: { type: 'cashToRunway', months: 2, discount: 0.15, cost: 0 } },
    { id: 'board_packet', label: '临时议程', description: '下个月紧急召开董事会', effect: { type: 'emergencyBoard' } },
  ],
  FUN_07: [
    { id: 'alliance', label: '跨部门联盟', description: '抽 3 选 2；下月 boss 收入 -15%', effect: { type: 'composite', effects: [{ type: 'drawSelect', draw: 3, keep: 2 }, { type: 'rivalDebuff', months: 1, rivalIncomeMult: 0.85 }] } },
  ],
  FUN_08: [
    { id: 'okr_reset', label: 'OKR 重置', description: '未来 3 个月 PE +10%，下个月董事会提前召开', effect: { type: 'composite', effects: [{ type: 'peBuff', value: 0.1, months: 3 }, { type: 'emergencyBoard' }] } },
  ],
  FUN_09: [
    { id: 'crunch', label: '冲刺窗口', description: '未来 1 个月 PE +25%，之后照常还债', effect: { type: 'peBuff', value: 0.25, months: 1 } },
  ],
  FUN_10: [
    { id: 'brand_moat', label: '品牌护城河', description: '未开战 boss 延后 3 个月，未来 2 月 PE +8%', effect: { type: 'composite', effects: [{ type: 'delayBoss', months: 3 }, { type: 'peBuff', value: 0.08, months: 2 }] } },
  ],
  FUN_11: [
    { id: 'user_festival', label: '用户节', description: '现金 -120，下月 boss 收入 -30%', cost: 120, effect: { type: 'rivalDebuff', months: 1, rivalIncomeMult: 0.7 } },
  ],
  FUN_12: [
    { id: 'debt_cleanup', label: '技术债大扫除', description: '未来 2 个月 burn -25%，抽 2 张', effect: { type: 'composite', effects: [{ type: 'cashToRunway', months: 2, discount: 0.25 }, { type: 'drawSelect', draw: 2, keep: 2 }] } },
  ],
}

export const EVENTS = [
  {
    id: 'angel-capital',
    name: '天使融资到账',
    tone: '增益',
    description: '投资人提前打款，但对短期成长有期望。',
    effectLines: ['立即 +¥10', '本月维持费 +20% (投资人要求扩张)'],
    cashDelta: 10,
    recruitExtra: 1,
    incomeMultiplier: 1,
    maintenanceMultiplier: 1.2,
  },
  {
    id: 'customer-consulting',
    name: '客户咨询',
    tone: '增益',
    description: '一批高意向客户主动找上门。',
    effectLines: ['本月产线收入 +15%', '销售相邻更容易放大'],
    cashDelta: 0,
    recruitExtra: 0,
    incomeMultiplier: 1.15,
    maintenanceMultiplier: 1,
  },
  {
    id: 'hiring-season',
    name: '招聘旺季',
    tone: '机会',
    description: '候选人质量和数量同步上升。',
    effectLines: ['招聘市场 +2', '战略预算不变'],
    cashDelta: 0,
    recruitExtra: 2,
    incomeMultiplier: 1,
    maintenanceMultiplier: 1,
  },
  {
    id: 'team-conflict',
    name: '团队冲突',
    tone: '风险',
    description: '沟通成本升高，管理资源被消耗。',
    effectLines: ['本月 AP 上限 -2', '产线仍可正常结算'],
    cashDelta: 0,
    apDelta: -2,
    recruitExtra: 0,
    incomeMultiplier: 1,
    maintenanceMultiplier: 1,
  },
  {
    id: 'industry-tailwind',
    name: '行业利好',
    tone: '增益',
    description: '市场窗口打开，所有收入被放大。',
    effectLines: ['本月 ¥ 收入 +20%'],
    cashDelta: 0,
    recruitExtra: 0,
    incomeMultiplier: 1.2,
    maintenanceMultiplier: 1,
  },
  {
    id: 'cash-crunch',
    name: '现金流危机',
    tone: '风险',
    description: '供应商账期收紧，维持费压力上升。',
    effectLines: ['本月维持费 x2', '律师/外包可免除'],
    cashDelta: 0,
    recruitExtra: 0,
    incomeMultiplier: 1,
    maintenanceMultiplier: 2,
  },

  // ============================================================================
  // M2.1b 补事件 +24 张 (总 30 张), 加强戏剧化波动
  // ============================================================================

  // ---- 增益类 +8 ----
  {
    id: 'media-spotlight',
    name: '媒体曝光',
    tone: '增益',
    description: '一篇深度报道点燃公众关注。',
    effectLines: ['本月收入 +30%'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 1.3, maintenanceMultiplier: 1,
  },
  {
    id: 'rd-bonanza',
    name: '风口产业',
    tone: '增益',
    description: '风口吹起，研发卡分获横财。',
    effectLines: ['本月研发部 ×2'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 1.2, maintenanceMultiplier: 1,
    deptBoost: { R: 2 },
  },
  {
    id: 'year-end-bonus',
    name: '跨年红利',
    tone: '增益',
    description: '跨年财务结余反哺运营。',
    effectLines: ['本月维持费 -100%'],
    cashDelta: 5, recruitExtra: 0,
    incomeMultiplier: 1, maintenanceMultiplier: 0,
  },
  {
    id: 'gov-subsidy',
    name: '政府补贴',
    tone: '增益',
    description: '高新技术企业认证下来，但合规审查也跟来了。',
    effectLines: ['立即 +¥30', '本月收入 -10%'],
    cashDelta: 30, recruitExtra: 0,
    incomeMultiplier: 0.9, maintenanceMultiplier: 1,
  },
  {
    id: 'competitor-collapse',
    name: '友商内乱',
    tone: '增益',
    description: '主要竞品高管出走，客户外溢。',
    effectLines: ['本月销售部 ×1.5'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 1.1, maintenanceMultiplier: 1,
    deptBoost: { S: 1.5 },
  },
  {
    id: 'big-client',
    name: '大客户签约',
    tone: '增益',
    description: '世界 500 强 LOGO 入手，但对接成本陡升。',
    effectLines: ['立即 +¥50', '本月维持费 +30%'],
    cashDelta: 50, recruitExtra: 0,
    incomeMultiplier: 1, maintenanceMultiplier: 1.3,
  },
  {
    id: 'kol-fire',
    name: '网红营销爆款',
    tone: '增益',
    description: '一条短视频带火品牌。',
    effectLines: ['本月销售相邻 +30%', '收入 +10%'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 1.1, maintenanceMultiplier: 1,
  },
  {
    id: 'industry-award',
    name: '行业奖项',
    tone: '增益',
    description: '年度最佳新锐企业。',
    effectLines: ['本月 ¥ +25%', '招聘市场 +1'],
    cashDelta: 0, recruitExtra: 1,
    incomeMultiplier: 1.25, maintenanceMultiplier: 1,
  },

  // ---- 风险类 +8 ----
  {
    id: 'black-swan',
    name: '黑天鹅事件',
    tone: '风险',
    description: '宏观因素突然恶化，但低谷期招到了便宜的人才。',
    effectLines: ['本月收入 -40%', '下月开局 AP +3 (危机后整顿)'],
    cashDelta: -20, recruitExtra: 0,
    apDelta: 3,
    incomeMultiplier: 0.6, maintenanceMultiplier: 1,
  },
  {
    id: 'key-employee-quit',
    name: '关键员工离职',
    tone: '风险',
    description: '核心高管被挖去竞品。',
    effectLines: ['本月手牌 -2'],
    cashDelta: -25, recruitExtra: 0,
    incomeMultiplier: 1, maintenanceMultiplier: 1,
    handDelta: -2,
  },
  {
    id: 'media-crisis',
    name: '媒体危机',
    tone: '风险',
    description: '负面新闻在社交平台发酵。',
    effectLines: ['本月维持费 ×3'],
    cashDelta: -30, recruitExtra: 0,
    incomeMultiplier: 0.9, maintenanceMultiplier: 3,
  },
  {
    id: 'cashflow-tight',
    name: '现金流紧张',
    tone: '风险',
    description: '应收账款迟迟未到，但出货量却创新高。',
    effectLines: ['立即 -¥45', '本月收入 +20%'],
    cashDelta: -45, recruitExtra: 0,
    incomeMultiplier: 1.2, maintenanceMultiplier: 1,
  },
  {
    id: 'team-burnout',
    name: '团队倦怠',
    tone: '风险',
    description: '连续加班导致效率断崖。',
    effectLines: ['本月 AP 上限 -3'],
    cashDelta: -20, recruitExtra: 0,
    apDelta: -3,
    incomeMultiplier: 1, maintenanceMultiplier: 1,
  },
  {
    id: 'rd-winter',
    name: '行业寒冬',
    tone: '风险',
    description: '资本市场对研发型公司估值打折。',
    effectLines: ['本月研发部 -50%'],
    cashDelta: -20, recruitExtra: 0,
    incomeMultiplier: 0.85, maintenanceMultiplier: 1,
    deptBoost: { R: 0.5 },
  },
  {
    id: 'customer-churn',
    name: '客户流失',
    tone: '风险',
    description: '一波客户被竞品挖走。',
    effectLines: ['本月销售部 -40%'],
    cashDelta: -25, recruitExtra: 0,
    incomeMultiplier: 0.9, maintenanceMultiplier: 1,
    deptBoost: { S: 0.6 },
  },
  {
    id: 'policy-tighten',
    name: '政策收紧',
    tone: '风险',
    description: '行业监管文件下来了。',
    effectLines: ['本月手牌上限 -2', '维持费 +50%'],
    cashDelta: -20, recruitExtra: 0,
    handLimitDelta: -2,
    incomeMultiplier: 1, maintenanceMultiplier: 1.5,
  },

  // ---- 机会类 +4 ----
  {
    id: 'industry-conference',
    name: '行业大会',
    tone: '机会',
    description: '行业人脉集中曝光，但需要预算赞助参展。',
    effectLines: ['招聘市场 +3', '本月维持费 +25%'],
    cashDelta: 0, recruitExtra: 3,
    incomeMultiplier: 1, maintenanceMultiplier: 1.25,
  },
  {
    id: 'vc-tailwind',
    name: '投融资风口',
    tone: '机会',
    description: '风险资本疯狂涌入本赛道。',
    effectLines: ['立即 +¥20'],
    cashDelta: 20, recruitExtra: 0,
    incomeMultiplier: 1, maintenanceMultiplier: 1,
  },
  {
    id: 'campus-season',
    name: '校招季',
    tone: '机会',
    description: '应届生集中入职的窗口。',
    effectLines: ['本月抽牌 +3'],
    cashDelta: 0, recruitExtra: 0,
    drawDelta: 3,
    incomeMultiplier: 1, maintenanceMultiplier: 1,
  },
  {
    id: 'internal-startup',
    name: '内部创业',
    tone: '机会',
    description: '抽出一个团队孵化新业务。',
    effectLines: ['本月 AP 上限 +3', '维持费 +50%'],
    cashDelta: 0, recruitExtra: 0,
    apDelta: 3,
    incomeMultiplier: 1.1, maintenanceMultiplier: 1.5,
  },

  // ---- 戏剧化 / 中性 +4 ----
  {
    id: 'investor-visit',
    name: '投资人来访',
    tone: '机会',
    description: '一切都要光鲜亮丽。',
    effectLines: ['本月 AP +3', '维持费 ×1.5'],
    cashDelta: 0, recruitExtra: 0,
    apDelta: 3,
    incomeMultiplier: 1, maintenanceMultiplier: 1.5,
  },
  {
    id: 'team-building',
    name: '团建活动',
    tone: '机会',
    description: '加深感情，但耽误一两天工作。',
    effectLines: ['本月 AP -1', '产出 +25%'],
    cashDelta: 0, recruitExtra: 0,
    apDelta: -1,
    incomeMultiplier: 1.25, maintenanceMultiplier: 1,
  },
  {
    id: 'overtime-season',
    name: '加班冲刺季',
    tone: '机会',
    description: '关键节点全员加班。',
    effectLines: ['维持费 ×2', '收入 ×1.5'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 1.5, maintenanceMultiplier: 2,
  },
  {
    id: 'remote-work',
    name: '远程办公',
    tone: '机会',
    description: '居家办公，灵活但松散。',
    effectLines: ['手牌上限 +2', '招聘市场 -1'],
    cashDelta: 0, recruitExtra: -1,
    handLimitDelta: 2,
    incomeMultiplier: 1, maintenanceMultiplier: 0.8,
  },
  {
    id: 'customer-referral',
    name: '老客户转介绍',
    tone: '增益',
    description: '满意客户主动介绍了新订单。',
    effectLines: ['本月收入 +10%', '招聘市场 +1'],
    cashDelta: 0, recruitExtra: 1,
    incomeMultiplier: 1.1, maintenanceMultiplier: 1,
  },
  {
    id: 'process-automation',
    name: '流程自动化',
    tone: '增益',
    description: '内部工具上线，重复劳动少了很多。',
    effectLines: ['本月维持费 -20%', '本月 AP +1'],
    cashDelta: 0, recruitExtra: 0,
    apDelta: 1,
    incomeMultiplier: 1, maintenanceMultiplier: 0.8,
  },
  {
    id: 'product-review',
    name: '产品评审会',
    tone: '机会',
    description: '团队暂时停下来复盘路线，短期慢一点，长期更稳。',
    effectLines: ['本月收入 -10%', '本月抽牌 +2'],
    cashDelta: 0, recruitExtra: 0,
    drawDelta: 2,
    incomeMultiplier: 0.9, maintenanceMultiplier: 1,
  },
  {
    id: 'channel-rebate',
    name: '渠道返利',
    tone: '机会',
    description: '渠道伙伴返了一笔账，但要求下月继续投入。',
    effectLines: ['立即 +¥18', '本月维持费 +10%'],
    cashDelta: 18, recruitExtra: 0,
    incomeMultiplier: 1, maintenanceMultiplier: 1.1,
  },
  {
    id: 'receivable-delay',
    name: '回款延迟',
    tone: '风险',
    description: '客户验收慢了半拍，账面业务还在，但现金到账变慢。',
    effectLines: ['立即 -¥18', '本月收入 +5%'],
    cashDelta: -18, recruitExtra: 0,
    incomeMultiplier: 1.05, maintenanceMultiplier: 1,
  },
  {
    id: 'cloud-bill-spike',
    name: '云服务账单飙升',
    tone: '风险',
    description: '用户增长带来了服务器账单，工程团队必须优化。',
    effectLines: ['立即 -¥22', '本月研发部 +20%'],
    cashDelta: -22, recruitExtra: 0,
    incomeMultiplier: 1, maintenanceMultiplier: 1.15,
    deptBoost: { R: 1.2 },
  },
  {
    id: 'hiring-misfire',
    name: '招聘误判',
    tone: '风险',
    description: '一个关键岗位试用期不合适，团队节奏被打乱。',
    effectLines: ['本月手牌 -1', '立即 -¥16'],
    cashDelta: -16, recruitExtra: 0,
    handDelta: -1,
    incomeMultiplier: 1, maintenanceMultiplier: 1,
  },
  {
    id: 'price-war',
    name: '竞品价格战',
    tone: '风险',
    description: '竞品突然降价抢客户，销售团队要用更高成本守住阵地。',
    effectLines: ['本月销售部 -20%', '维持费 +20%'],
    cashDelta: 0, recruitExtra: 0,
    incomeMultiplier: 0.95, maintenanceMultiplier: 1.2,
    deptBoost: { S: 0.8 },
  },
]

const QUARTERLY_EVENT_COPY = {
  'angel-capital': ['天使投资人群聊忽然很热', '凌晨三点，投资人突然转来三篇行业报告，并表示“这个季度可以冲”。'],
  'customer-consulting': ['甲方预算季提前到来', '采购系统刚打开，销售同学的微信就开始连续震动。'],
  'hiring-season': ['大厂组织调整，人才市场开闸', '简历像雪片一样飞来，其中一半写着“负责过核心模块”。'],
  'team-conflict': ['远程会议软件成为主要战场', '大家都在说“我补充一点”，但没人知道原议题是什么。'],
  'industry-tailwind': ['赛道突然被写进十篇深度研报', '投资人突然都懂了这个行业，虽然昨天还念错名字。'],
  'cash-crunch': ['账期收紧，财务开始盯咖啡豆', '供应商说理解创业不易，所以先付钱再理解。'],
  'media-spotlight': ['行业榜单一夜刷屏', '一篇榜单让客户、候选人和竞争对手同时找上门。'],
  'rd-bonanza': ['大模型发布会 17 连发', '投资人突然都懂 AGI，研发同学突然都不够用了。'],
  'year-end-bonus': ['降本增效春风吹满地', '办公室咖啡先被优化，报表倒是好看了一点。'],
  'gov-subsidy': ['补贴窗口打开三小时', '表格很多，章很多，但钱也确实有一点。'],
  'competitor-collapse': ['友商 All Hands 开成告别会', '客户经理的电话第一次比闹钟还准。'],
  'big-client': ['大客户年度预算重排', 'Logo 很香，需求文档也很厚。'],
  'kol-fire': ['全网都在复刻同一个标题', '增长团队说这不是玄学，这是“内容势能”。'],
  'industry-award': ['年度颁奖夜灯光很贵', '奖杯不重，但拿着它招聘会好谈不少。'],
  'black-swan': ['宏观天气预报改成暴雨', '大家都在找伞，结果发现伞也涨价了。'],
  'key-employee-quit': ['核心同学朋友圈更新“新的开始”', 'HR 点了赞，CEO 沉默了三秒。'],
  'media-crisis': ['热搜词条开始自己繁殖', '公关稿还没写完，评论区已经写完了。'],
  'cashflow-tight': ['回款群里只剩自动回复', '业务很好，现金很远，财务很安静。'],
  'team-burnout': ['工位区出现连续哈欠传染链', '大家都很努力，只是努力的方向变成了找假期。'],
  'rd-winter': ['技术路线被资本市场临时降温', '昨天叫壁垒，今天叫研发费用。'],
  'customer-churn': ['客户群里开始讨论“平替”', '销售说关系还在，合同说先等等。'],
  'policy-tighten': ['监管文件更新到第八版', '法务说不急，只是所有按钮都要改文案。'],
  'industry-conference': ['行业大会酒店房价翻倍', '所有人都说来学习，所有人都带了销售材料。'],
  'vc-tailwind': ['资本市场再次相信故事', '只要 PPT 里有飞轮，会议室就有咖啡。'],
  'campus-season': ['校招季带来新鲜肝度', '应届生问的问题很真诚，也很难回答。'],
  'internal-startup': ['内部创业擂台赛开锣', '每个团队都说自己是第二增长曲线。'],
  'investor-visit': ['投资人突击参观办公室', '所有白板都临时写上了战略。'],
  'team-building': ['季度团建预算没被砍完', '大家在草坪上建立信任，回来继续改需求。'],
  'overtime-season': ['季度 OKR 进入最后冲刺', '会议室灯亮到很晚，咖啡机也开始怀疑人生。'],
  'remote-work': ['远程办公再次流行', '效率提升了，找人也更像开盲盒了。'],
  'customer-referral': ['老客户突然愿意介绍朋友', '这可能是口碑，也可能是他们终于有人一起吐槽。'],
  'process-automation': ['流程机器人上线第一周', '它不会抱怨，也不会忘记催你填表。'],
  'product-review': ['季度产品评审拉满日历', '路线图终于像路线图，不像许愿池。'],
  'channel-rebate': ['渠道返利到账但附带小字', '钱是真的，下一季度 KPI 也是真的。'],
  'receivable-delay': ['验收流程进入“快了”阶段', '客户说本周一定走完流程，没说是哪一周。'],
  'cloud-bill-spike': ['云账单像产品增长一样增长', '增长同学很开心，财务同学不太开心。'],
  'hiring-misfire': ['试用期复盘会气氛友好', '友好到大家都不好意思说真话。'],
  'price-war': ['平台爸爸改算法，补贴开始满天飞', '昨天的增长秘籍今天成违规，竞品还顺手降价。'],
}

const EVENT_TRACK_WEIGHTS = {
  ai: ['rd-bonanza', 'cloud-bill-spike', 'product-review', 'industry-conference', 'internal-startup', 'policy-tighten'],
  growth: ['customer-consulting', 'industry-tailwind', 'media-spotlight', 'kol-fire', 'channel-rebate', 'price-war', 'customer-churn'],
  ops: ['process-automation', 'team-building', 'remote-work', 'receivable-delay', 'hiring-misfire', 'team-conflict', 'cashflow-tight'],
}

EVENTS.forEach((event) => {
  const copy = QUARTERLY_EVENT_COPY[event.id]
  if (copy) {
    event.name = copy[0]
    event.description = copy[1]
  }
  event.effectLines = (event.effectLines ?? []).map((line) => line.replace(/本月/g, '本季度'))
  event.trackWeights = {
    ai: EVENT_TRACK_WEIGHTS.ai.includes(event.id) ? 1.7 : 1,
    growth: EVENT_TRACK_WEIGHTS.growth.includes(event.id) ? 1.7 : 1,
    ops: EVENT_TRACK_WEIGHTS.ops.includes(event.id) ? 1.7 : 1,
  }
})

export const BOSS_EVENTS = [
  {
    id: 'boss-series-a-roadshow',
    name: 'Boss · A 轮路演',
    tone: 'Boss',
    description: '投资人只看核心位置有没有能扛场的人。',
    effectLines: ['关末检查: P3 必须是经理级或以上', '不满足则本关无法达标'],
    incomeMultiplier: 1,
    maintenanceMultiplier: 1,
    bossRule: { type: 'p3_min_tier', minTier: '经理' },
  },
  {
    id: 'boss-series-b-diligence',
    name: 'Boss · B 轮尽调',
    tone: 'Boss',
    description: '尽调团队进场，成本翻倍，但好数据会被放大。',
    effectLines: ['本月收入 +30%', '本月维持费 x2'],
    incomeMultiplier: 1.3,
    maintenanceMultiplier: 2,
    bossRule: { type: 'none' },
  },
  {
    id: 'boss-series-c-negotiation',
    name: 'Boss · C 轮谈判',
    tone: 'Boss',
    description: '谈判桌只留最关键的人，临场可用手牌骤减。',
    effectLines: ['进入 Boss 月时手牌 -3', '被移走的牌回到牌堆'],
    incomeMultiplier: 1,
    maintenanceMultiplier: 1,
    handDelta: -3,
    bossRule: { type: 'none' },
  },
]

export const SMALL_AFFIXES = [
  { id: 'AFF_S_01', name: '加班狂', effects: ['BASE_OUTPUT: +30%'] },
  { id: 'AFF_S_02', name: '性价比', effects: ['COST: -40%'] },
  { id: 'AFF_S_03', name: '资深', effects: ['COST: +50%', 'BASE_OUTPUT: +25%'] },
  { id: 'AFF_S_05', name: '团魂', effects: ['SAME_DEPT_ADJ_EXTRA: +10%'] },
  { id: 'AFF_S_07', name: '完美主义', effects: ['SELF_IF_P3: +25%'] },
  { id: 'AFF_S_08', name: '收割者', effects: ['SELF_IF_P5: +30%'] },
  { id: 'AFF_S_10', name: '学霸', effects: ['SELF_IF_ADJ_FUN: +20%'] },
]

export const LARGE_AFFIXES = [
  { id: 'AFF_L_02', name: '双倍工作', effects: ['NO_COOLDOWN'] },
  { id: 'AFF_L_05', name: '化学反应', effects: ['SAME_DEPT_ADJ_EXTRA: +25%'] },
  { id: 'AFF_L_08', name: '大佬光环', effects: ['LINE_ALL: +15%'] },
  { id: 'AFF_L_10', name: '一颗螺丝钉', effects: ['LINE_ALL: +12%'] },
  { id: 'AFF_L_11', name: '跨界鬼才', effects: ['IF_ALL_THREE_DEPT_IN_LINE: LINE_ALL: x1.5'] },
]

export const CARD_TEMPLATES = [
  {
    id: 'EMP_R_01',
    name: '研发专员',
    type: 'emp',
    dept: 'R',
    tier: '专员',
    rarity: 'common',
    unlockLevel: 1,
    ap: 1,
    costSpec: '5 ±10%',
    baseOutputSpec: '20 ±10%',
    effects: ['RIGHT: +10% ±10%'],
    flavor: '刚毕业的小伙子，加班贼狠',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_02',
    name: '研发经理',
    type: 'emp',
    dept: 'R',
    tier: '经理',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '11 ±10%',
    baseOutputSpec: '45 ±10%',
    effects: ['RIGHT: +25% ±10%'],
    flavor: '技术骨干升上来的，能写代码也能带人',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_03',
    name: '研发总监',
    type: 'emp',
    dept: 'R',
    tier: '总监',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 4,
    costSpec: '22 ±15%',
    baseOutputSpec: '85 ±15%',
    effects: ['RIGHT: +40% ±15%', 'SELF_IF_P1: +20%'],
    flavor: '技术线最高决策者，路线图全靠他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_04',
    name: '算法专家',
    type: 'emp',
    dept: 'R',
    tier: '专员',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 2,
    costSpec: '15 ±15%',
    baseOutputSpec: '35 ±15%',
    effects: ['SELF_IF_RIGHT_FUN: x1.5', 'RIGHT: +15% ±15%'],
    flavor: '懂数据、懂模型，但不太会说话',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_05',
    name: '全栈工程师',
    type: 'emp',
    dept: 'R',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 3,
    costSpec: '17 ±15%',
    baseOutputSpec: '55 ±15%',
    effects: ['BOTH: +15% ±15%'],
    flavor: '一个人顶三个用，但跳槽风险大',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_06',
    name: '架构师',
    type: 'emp',
    dept: 'R',
    tier: '总监',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 4,
    costSpec: '25 ±15%',
    baseOutputSpec: '75 ±15%',
    effects: ['SAME_DEPT_ADJ: +30%', 'RIGHT: +20% ±15%'],
    flavor: '图画得比代码多，但你不能没有他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_07',
    name: '技术 VP',
    type: 'emp',
    dept: 'R',
    tier: 'VP',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 5,
    costSpec: '35 ±20%',
    baseOutputSpec: '120 ±20%',
    effects: ['LINE_ALL_R: +25%', 'RIGHT: +30% ±20%'],
    flavor: '技术线副总裁，话不多但说话顶用',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_08',
    name: '首席科学家',
    type: 'emp',
    dept: 'R',
    tier: 'VP',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 5,
    costSpec: '45 ±25%',
    baseOutputSpec: '140 ±25%',
    effects: ['SELF_IF_P3: BOTH: +40%', 'MONTH_STAR_RATE: +5%'],
    flavor: '顶着 PhD 学位的明星，估值看脸的关键',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_09',
    name: '极客实习生',
    type: 'emp',
    dept: 'R',
    tier: '专员',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 2,
    costSpec: '10 ±20%',
    baseOutputSpec: '38 ±20%',
    effects: ['RIGHT: +30% ±20%', 'TRIGGER: SELF_IF_LEFT_DEPT_R: SELF: x2'],
    flavor: '成本极低产出极高，但容易被挖',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_01',
    name: '销售专员',
    type: 'emp',
    dept: 'S',
    tier: '专员',
    rarity: 'common',
    unlockLevel: 1,
    ap: 1,
    costSpec: '5 ±10%',
    baseOutputSpec: '20 ±10%',
    effects: ['LEFT: +10% ±10%'],
    flavor: '电话打到嗓子哑，提成是动力',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_02',
    name: '销售经理',
    type: 'emp',
    dept: 'S',
    tier: '经理',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '11 ±10%',
    baseOutputSpec: '45 ±10%',
    effects: ['LEFT: +20% ±10%'],
    flavor: '带一支小队，月度冠军常客',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_03',
    name: '销售总监',
    type: 'emp',
    dept: 'S',
    tier: '总监',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 4,
    costSpec: '22 ±15%',
    baseOutputSpec: '85 ±15%',
    effects: ['LEFT: +35% ±15%', 'SELF_IF_P5: x1.5'],
    flavor: '客户全在他手机里，公司离不开他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_04',
    name: '大客户经理',
    type: 'emp',
    dept: 'S',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 3,
    costSpec: '17 ±15%',
    baseOutputSpec: '55 ±15%',
    effects: ['LEFT: +15% ±15%', 'SELF_IF_LEFT_DEPT_R: x1.4'],
    flavor: '专啃硬骨头，订单一签就是几百万',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_05',
    name: 'BD 专员',
    type: 'emp',
    dept: 'S',
    tier: '专员',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 2,
    costSpec: '13 ±15%',
    baseOutputSpec: '30 ±15%',
    effects: ['LEFT: +12% ±15%', 'MONTH_BONUS: +¥3'],
    flavor: 'BD 全靠人脉，吃饭喝酒签合作',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_06',
    name: '电商运营',
    type: 'emp',
    dept: 'S',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '18 ±15%',
    baseOutputSpec: '50 ±15%',
    effects: ['BOTH: +12% ±15%', 'TRIGGER: SELF_IF_LINE_HAS_FUN: x1.3'],
    flavor: 'GMV 主义者，永远在 ABtest',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_07',
    name: '销售 VP',
    type: 'emp',
    dept: 'S',
    tier: 'VP',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 5,
    costSpec: '35 ±20%',
    baseOutputSpec: '120 ±20%',
    effects: ['LINE_ALL_S: +25%', 'LEFT: +30% ±20%'],
    flavor: '销售一把手，KPI 拍板靠他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_08',
    name: '销售之神',
    type: 'emp',
    dept: 'S',
    tier: 'VP',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 5,
    costSpec: '45 ±25%',
    baseOutputSpec: '140 ±25%',
    effects: ['SELF_IF_P5: SELF: x2.5', 'LEFT: +30% ±25%'],
    flavor: '传说级销售，开口就是大单',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_09',
    name: '客户成功',
    type: 'emp',
    dept: 'S',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '17 ±15%',
    baseOutputSpec: '50 ±15%',
    effects: ['LEFT: +18% ±15%', 'SAME_DEPT_ADJ: +¥2'],
    flavor: '续约率王者，老客户都认他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_01',
    name: '运营专员',
    type: 'emp',
    dept: 'O',
    tier: '专员',
    rarity: 'common',
    unlockLevel: 1,
    ap: 1,
    costSpec: '5 ±10%',
    baseOutputSpec: '22 ±10%',
    effects: ['SAME_DEPT_ADJ: +¥1'],
    flavor: 'Excel 大师，表格能开花',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_02',
    name: '运营经理',
    type: 'emp',
    dept: 'O',
    tier: '经理',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '11 ±10%',
    baseOutputSpec: '48 ±10%',
    effects: ['SAME_DEPT_ADJ: +¥2', 'BOTH: +10% ±10%'],
    flavor: '流程优化狂魔，省钱的能手',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_03',
    name: '运营总监',
    type: 'emp',
    dept: 'O',
    tier: '总监',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 4,
    costSpec: '22 ±15%',
    baseOutputSpec: '85 ±15%',
    effects: ['SAME_DEPT_ADJ: +¥3', 'SELF_IF_P3: BOTH: +25%'],
    flavor: '公司大管家，老板甩手掌柜全靠他',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_04',
    name: 'HR 经理',
    type: 'emp',
    dept: 'O',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 3,
    costSpec: '16 ±15%',
    baseOutputSpec: '45 ±15%',
    effects: ['LINE_ALL: +8% ±15%', 'MONTH_BONUS: +¥2'],
    flavor: '招聘留人都是他，但绩效面谈让人怕',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_05',
    name: '财务经理',
    type: 'emp',
    dept: 'O',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 3,
    costSpec: '18 ±15%',
    baseOutputSpec: '40 ±15%',
    effects: ['MONTH_BONUS: +¥5', 'BOTH: +8% ±15%'],
    flavor: '管钱袋子的人，老板真正的朋友',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_06',
    name: '项目经理 PM',
    type: 'emp',
    dept: 'O',
    tier: '经理',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '17 ±15%',
    baseOutputSpec: '50 ±15%',
    effects: ['BOTH: +20% ±15%', 'TRIGGER: SELF_IF_LEFT_DEPT_R_AND_RIGHT_DEPT_S: SELF: x1.5'],
    flavor: '甘特图战神，跨部门翻译机',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_07',
    name: '运营 VP / COO',
    type: 'emp',
    dept: 'O',
    tier: 'VP',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 5,
    costSpec: '38 ±20%',
    baseOutputSpec: '115 ±20%',
    effects: ['LINE_ALL: +15%', 'MONTH_BONUS: +¥10'],
    flavor: '首席运营官，公司日常运转的中枢',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_08',
    name: '行政总管',
    type: 'emp',
    dept: 'O',
    tier: '总监',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 4,
    costSpec: '20 ±15%',
    baseOutputSpec: '70 ±15%',
    effects: ['MONTH_NO_MAINTAIN', 'BOTH: +10% ±15%'],
    flavor: '省下的就是赚到的',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_09',
    name: '数据分析师',
    type: 'emp',
    dept: 'O',
    tier: '专员',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 2,
    costSpec: '13 ±15%',
    baseOutputSpec: '32 ±15%',
    effects: ['BOTH: +18% ±15%', 'TRIGGER: SELF_IF_ADJ_FUN: SELF: x1.4'],
    flavor: 'SQL 写得比情书还多，数字驱动决策',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_01',
    name: '市场调研',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '7 ±10%',
    baseOutputSpec: '0',
    effects: ['BOTH: +25% ±10%'],
    flavor: '了解客户才能搞定客户',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'FUN_02',
    name: '产品冲刺',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 1,
    ap: 3,
    costSpec: '9 ±10%',
    baseOutputSpec: '0',
    effects: ['ADJ_R: x2 ±10%'],
    flavor: '全部门拼一把，发版日就是验货日',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'FUN_03',
    name: '团队建设',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '8 ±10%',
    baseOutputSpec: '0',
    effects: ['LINE_ALL: +¥15 ±10%'],
    flavor: '团建不是吃饭，是凝聚力投资',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'FUN_04',
    name: '产品推广',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 1,
    ap: 3,
    costSpec: '9 ±10%',
    baseOutputSpec: '0',
    effects: ['ADJ_S: x2 ±10%'],
    flavor: '酒香也怕巷子深，推广要趁早',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'FUN_05',
    name: '数据分析',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 2,
    ap: 2,
    costSpec: '7 ±10%',
    baseOutputSpec: '0',
    effects: ['LEFT: +30% ±10%'],
    flavor: '用数据说话，向上汇报必备',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_06',
    name: '流程优化',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 2,
    ap: 2,
    costSpec: '7 ±10%',
    baseOutputSpec: '0',
    effects: ['RIGHT: +30% ±10%'],
    flavor: '把繁琐变简单，把简单变高效',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_07',
    name: '跨部门协作',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '13 ±15%',
    baseOutputSpec: '0',
    effects: ['TRIGGER: LEFT_DEPT != RIGHT_DEPT: BOTH: +40% ±15%'],
    flavor: '墙太厚要敲掉，孤岛太多要修桥',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_08',
    name: 'OKR 制定',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '13 ±15%',
    baseOutputSpec: '0',
    effects: ['LINE_ALL: +15% ±15%', 'MONTH_STAR_RATE: +3%'],
    flavor: '目标对齐了，效率才有意义',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_09',
    name: '加班动员',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'common',
    unlockLevel: 2,
    ap: 2,
    costSpec: '7 ±10%',
    baseOutputSpec: '0',
    effects: ['LINE_ALL: +20% ±10%'],
    flavor: '冲一波，但下个月别怪我',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_10',
    name: '品牌建设',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '15 ±15%',
    baseOutputSpec: '0',
    effects: ['BOTH: +20% ±15%', 'MONTH_STAR_RATE: +8%'],
    flavor: '品牌即资产，长期主义的体现',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_11',
    name: '用户运营活动',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '14 ±15%',
    baseOutputSpec: '0',
    effects: ['ADJ_S: +50% ±15%', 'MONTH_BONUS: +¥10'],
    flavor: '拉新促活，私域引流的标配',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'FUN_12',
    name: '技术债务清理',
    type: 'fun',
    dept: 'NONE',
    tier: '功能',
    rarity: 'rare',
    unlockLevel: 4,
    ap: 3,
    costSpec: '14 ±15%',
    baseOutputSpec: '0',
    effects: ['ADJ_R: +50% ±15%'],
    flavor: '前人欠的债，后人还，但还完爽',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_01',
    name: '律师事务所',
    type: 'srv',
    dept: 'NONE',
    tier: '基础',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '8 ±10%',
    baseOutputSpec: '0',
    effects: ['MONTH_NO_MAINTAIN'],
    flavor: '合同审查 + 风险规避，省钱的法宝',
    inStarterDeck: true,
    inRecruitPool: true,
  },
  {
    id: 'SRV_02',
    name: '税务筹划',
    type: 'srv',
    dept: 'NONE',
    tier: '基础',
    rarity: 'common',
    unlockLevel: 1,
    ap: 2,
    costSpec: '8 ±10%',
    baseOutputSpec: '0',
    effects: ['MONTH_STAR_RATE: +5%'],
    flavor: '合法节税是企业必修课',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_03',
    name: '外部咨询',
    type: 'srv',
    dept: 'NONE',
    tier: '进阶',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 4,
    costSpec: '19 ±15%',
    baseOutputSpec: '0',
    effects: ['LINE_XMULT: x1.3 ±15%'],
    flavor: 'Mck.ey 一份报告，半年战略不愁',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_04',
    name: '融资顾问',
    type: 'srv',
    dept: 'NONE',
    tier: '进阶',
    rarity: 'rare',
    unlockLevel: 2,
    ap: 3,
    costSpec: '15 ±15%',
    baseOutputSpec: '0',
    effects: ['MONTH_BONUS: +¥15 ±15%', 'MONTH_STAR_RATE: +3%'],
    flavor: '对接 VC、修 BP，专业的人做专业的事',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_05',
    name: '管理咨询',
    type: 'srv',
    dept: 'NONE',
    tier: '顶级',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 5,
    costSpec: '32 ±20%',
    baseOutputSpec: '0',
    effects: ['MONTH_AP: +5'],
    flavor: '组织架构 + 流程再造的大手术',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_06',
    name: '战略顾问',
    type: 'srv',
    dept: 'NONE',
    tier: '顶级',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 5,
    costSpec: '32 ±20%',
    baseOutputSpec: '0',
    effects: ['LINE_ALL: +30% ±20%'],
    flavor: '看远一些，走稳一些',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_07',
    name: 'PR 公关',
    type: 'srv',
    dept: 'NONE',
    tier: '进阶',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '15 ±15%',
    baseOutputSpec: '0',
    effects: ['MONTH_STAR_RATE: +10%'],
    flavor: '口碑、热度、声誉，都是真金白银',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_08',
    name: 'HR 外包',
    type: 'srv',
    dept: 'NONE',
    tier: '基础',
    rarity: 'common',
    unlockLevel: 2,
    ap: 2,
    costSpec: '9 ±10%',
    baseOutputSpec: '0',
    effects: ['MONTH_NO_MAINTAIN', 'BOTH: +5% ±10%'],
    flavor: '把杂活外包出去，专注主业',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_09',
    name: '投行顾问',
    type: 'srv',
    dept: 'NONE',
    tier: '顶级',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 5,
    costSpec: '40 ±25%',
    baseOutputSpec: '0',
    effects: ['MONTH_BONUS: +¥30 ±25%', 'MONTH_STAR_RATE: +15%'],
    flavor: '上市路上的必经合作伙伴',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'SRV_10',
    name: '法律团队',
    type: 'srv',
    dept: 'NONE',
    tier: '进阶',
    rarity: 'rare',
    unlockLevel: 3,
    ap: 3,
    costSpec: '16 ±15%',
    baseOutputSpec: '0',
    effects: ['MONTH_NO_MAINTAIN', 'LINE_ALL: +10% ±15%'],
    flavor: '升级版律师，覆盖知识产权、并购',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  // ===== 传奇卡 (仅董事会会议·投资部刷出, 详见 BOARD_MEETING_DESIGN.md §3) =====
  {
    id: 'LEG_R_01',
    name: '诺贝尔奖得主',
    type: 'emp',
    dept: 'R',
    tier: 'CXO',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 5,
    costSpec: '60 ±30%',
    baseOutputSpec: '180 ±30%',
    effects: ['SELF_IF_P3: BOTH: x2', 'LINE_ALL: +20% ±30%', 'MONTH_STAR_RATE: +10%'],
    flavor: '行业天花板，能让对手直接出局',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'LEG_S_01',
    name: '销冠之神',
    type: 'emp',
    dept: 'S',
    tier: 'CXO',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 5,
    costSpec: '55 ±30%',
    baseOutputSpec: '170 ±30%',
    effects: ['SAME_DEPT_S_ADJ: +50%', 'LINE_ALL_S_X: x1.5', 'MONTH_BONUS: +¥50 ±30%'],
    flavor: '一年只服务一家公司',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'LEG_O_01',
    name: '六西格玛大师',
    type: 'emp',
    dept: 'O',
    tier: 'CXO',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 5,
    costSpec: '50 ±30%',
    baseOutputSpec: '150 ±30%',
    effects: ['LINE_ALL: x1.4', 'MONTH_NO_MAINTAIN', 'SAME_DEPT_O_ADJ: +30%'],
    flavor: '所到之处皆为黑带',
    inStarterDeck: false,
    inRecruitPool: false,
  },

  // ============================================================================
  // M2.1b 补卡: 精英 +6 / 史诗 +12 / 传奇 +7
  // 设计原则: 不再是 RIGHT/LEFT +X% 的同形, 强调"机制颠覆"
  // ============================================================================

  // ---- 精英 +6 (每部门 2 张) ----
  {
    id: 'EMP_R_10',
    name: '黑客马拉松',
    type: 'emp',
    dept: 'R',
    tier: '专员',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 3,
    costSpec: '18 ±20%',
    baseOutputSpec: '42 ±20%',
    effects: ['ADJ_R: +60% ±20%', 'SELF_IF_LEFT_DEPT_R: SELF: x1.5'],
    flavor: '48 小时内造出 demo 的疯子',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_11',
    name: '专利律师',
    type: 'emp',
    dept: 'R',
    tier: '经理',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 3,
    costSpec: '20 ±20%',
    baseOutputSpec: '38 ±20%',
    effects: ['LINE_ALL_R: +¥8 ±20%', 'MONTH_STAR_RATE: +5%'],
    flavor: '把每一行代码都变成护城河',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_10',
    name: '展会专家',
    type: 'emp',
    dept: 'S',
    tier: '经理',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 3,
    costSpec: '18 ±20%',
    baseOutputSpec: '40 ±20%',
    effects: ['LINE_ALL_S: +¥8 ±20%', 'MONTH_BONUS: +¥10'],
    flavor: '一场展会换三个 LOI',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_11',
    name: '合伙人销售',
    type: 'emp',
    dept: 'S',
    tier: '总监',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 4,
    costSpec: '24 ±20%',
    baseOutputSpec: '55 ±20%',
    effects: ['SAME_DEPT_ADJ: +40%', 'LEFT: +30% ±20%'],
    flavor: '客户专找他签单',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_10',
    name: '精益顾问',
    type: 'emp',
    dept: 'O',
    tier: '经理',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 3,
    costSpec: '18 ±20%',
    baseOutputSpec: '30 ±20%',
    effects: ['MONTH_NO_MAINTAIN', 'LINE_ALL: +10% ±15%'],
    flavor: '砍掉一切不创造价值的步骤',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_11',
    name: '数据科学家',
    type: 'emp',
    dept: 'O',
    tier: '总监',
    rarity: 'elite',
    unlockLevel: 4,
    ap: 4,
    costSpec: '24 ±20%',
    baseOutputSpec: '50 ±20%',
    effects: ['SELF_IF_P3: BOTH: +30%', 'BOTH: +15% ±20%'],
    flavor: 'AB Test 跑 24 小时就拍板',
    inStarterDeck: false,
    inRecruitPool: true,
  },

  // ---- 史诗 +12 (每部门 4 张) ----
  // R 部门 4 张
  {
    id: 'EMP_R_12',
    name: 'CTO',
    type: 'emp',
    dept: 'R',
    tier: 'CXO',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 5,
    costSpec: '48 ±25%',
    baseOutputSpec: '120 ±25%',
    effects: ['LINE_ALL_R: x1.5', 'SELF_IF_P3: BOTH: +50%'],
    flavor: '架构、招聘、布道一肩挑',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_13',
    name: 'AI 研究员',
    type: 'emp',
    dept: 'R',
    tier: 'VP',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 4,
    costSpec: '42 ±25%',
    baseOutputSpec: '100 ±25%',
    effects: ['SELF_IF_P3: LINE_ALL: +30%', 'BOTH: +20% ±25%'],
    flavor: '论文产出比商业产出还重要',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_14',
    name: '开源大牛',
    type: 'emp',
    dept: 'R',
    tier: '总监',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 3,
    costSpec: '36 ±25%',
    baseOutputSpec: '90 ±25%',
    effects: ['SELF_IF_LEFT_DEPT_R: SELF: x2', 'RIGHT: +35% ±25%'],
    flavor: 'GitHub 上有 10k+ stars',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_R_15',
    name: '极客天才',
    type: 'emp',
    dept: 'R',
    tier: '专员',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 2,
    costSpec: '24 ±25%',
    baseOutputSpec: '70 ±25%',
    effects: ['SELF_IF_LINE_HAS_FUN: SELF: x2', 'ADJ_R: +40% ±25%'],
    flavor: '低薪高产出的代码狂人',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  // S 部门 4 张
  {
    id: 'EMP_S_12',
    name: 'CMO',
    type: 'emp',
    dept: 'S',
    tier: 'CXO',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 5,
    costSpec: '48 ±25%',
    baseOutputSpec: '120 ±25%',
    effects: ['LINE_ALL_S: x1.5', 'MONTH_BONUS: +¥20'],
    flavor: '砸品牌就为了一个数字',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_13',
    name: 'KOL 矩阵',
    type: 'emp',
    dept: 'S',
    tier: 'VP',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 4,
    costSpec: '40 ±25%',
    baseOutputSpec: '95 ±25%',
    effects: ['SELF_IF_P5: SELF: x3', 'LEFT: +40% ±25%'],
    flavor: '一条视频带火一个品类',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_14',
    name: '金牌销售',
    type: 'emp',
    dept: 'S',
    tier: '总监',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 3,
    costSpec: '35 ±25%',
    baseOutputSpec: '85 ±25%',
    effects: ['LEFT: +50% ±25%', 'SAME_DEPT_ADJ: +30%'],
    flavor: '靠 Excel 和酒桌打天下',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_S_15',
    name: '客户成功 VP',
    type: 'emp',
    dept: 'S',
    tier: 'VP',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 4,
    costSpec: '38 ±25%',
    baseOutputSpec: '80 ±25%',
    effects: ['LINE_ALL: +¥15 ±25%', 'BOTH: +25% ±25%'],
    flavor: 'NPS 是公司的生命线',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  // O 部门 4 张
  {
    id: 'EMP_O_12',
    name: 'COO',
    type: 'emp',
    dept: 'O',
    tier: 'CXO',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 5,
    costSpec: '46 ±25%',
    baseOutputSpec: '110 ±25%',
    effects: ['LINE_ALL: x1.4', 'MONTH_NO_MAINTAIN'],
    flavor: 'CEO 不在时她就是 CEO',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_13',
    name: '精益大师',
    type: 'emp',
    dept: 'O',
    tier: 'VP',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 4,
    costSpec: '40 ±25%',
    baseOutputSpec: '95 ±25%',
    effects: ['MONTH_NO_MAINTAIN', 'LINE_ALL: +20% ±25%'],
    flavor: '砍掉一半员工产出反而翻倍',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_14',
    name: 'OD 顾问',
    type: 'emp',
    dept: 'O',
    tier: '总监',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 3,
    costSpec: '34 ±25%',
    baseOutputSpec: '85 ±25%',
    effects: ['SAME_DEPT_ADJ: +60%', 'LINE_ALL: +5%'],
    flavor: '组织设计、KPI 重构、文化变革',
    inStarterDeck: false,
    inRecruitPool: true,
  },
  {
    id: 'EMP_O_15',
    name: '财务总监',
    type: 'emp',
    dept: 'O',
    tier: '总监',
    rarity: 'epic',
    unlockLevel: 6,
    ap: 4,
    costSpec: '38 ±25%',
    baseOutputSpec: '75 ±25%',
    effects: ['MONTH_BONUS: +¥25 ±25%', 'MONTH_NO_MAINTAIN'],
    flavor: '盘活每一分钱',
    inStarterDeck: false,
    inRecruitPool: true,
  },

  // ---- 传奇 +7 (4 张员工 + 3 张跨类) ----
  {
    id: 'LEG_R_02',
    name: '图灵奖得主',
    type: 'emp',
    dept: 'R',
    tier: 'CXO',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 5,
    costSpec: '70 ±30%',
    baseOutputSpec: '200 ±30%',
    effects: ['LINE_ALL_R: x2', 'SELF_IF_P3: BOTH: x2'],
    flavor: '诺奖得主只是他的学生',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'LEG_S_02',
    name: '乔布斯式 CEO',
    type: 'emp',
    dept: 'S',
    tier: 'CXO',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 5,
    costSpec: '68 ±30%',
    baseOutputSpec: '190 ±30%',
    effects: ['LINE_ALL: x1.5', 'SELF_IF_P3: LINE_ALL: +50%'],
    flavor: '产品 + 营销 + 现实扭曲力场',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'LEG_O_02',
    name: '德鲁克再世',
    type: 'emp',
    dept: 'O',
    tier: 'CXO',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 4,
    costSpec: '60 ±30%',
    baseOutputSpec: '150 ±30%',
    effects: ['MONTH_NO_MAINTAIN', 'LINE_ALL: +¥30 ±30%'],
    flavor: '管理学之父在世',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'LEG_M_01',
    name: '连续创业者',
    type: 'emp',
    dept: 'NONE',
    tier: 'CXO',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 5,
    costSpec: '65 ±30%',
    baseOutputSpec: '170 ±30%',
    effects: ['LINE_ALL: x1.6', 'IF_ALL_THREE_DEPT_IN_LINE: LINE_XMULT: x1.5'],
    flavor: '已经卖出过 3 家独角兽',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'SRV_LEG_01',
    name: '麦肯锡战略',
    type: 'srv',
    dept: 'NONE',
    tier: '顶级',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 5,
    costSpec: '55 ±30%',
    baseOutputSpec: '0',
    effects: ['LINE_XMULT: x2 ±30%', 'MONTH_BONUS: +¥50'],
    flavor: '咨询界的最高荣誉',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'FUN_LEG_01',
    name: '黑天鹅基金',
    type: 'fun',
    dept: 'NONE',
    tier: '顶级',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 4,
    costSpec: '50 ±30%',
    baseOutputSpec: '0',
    effects: ['LINE_XMULT: x3', 'MONTH_BONUS: +¥30'],
    flavor: '反脆弱才是真正的护城河',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'FUN_LEG_02',
    name: '专利墙战略',
    type: 'fun',
    dept: 'NONE',
    tier: '顶级',
    rarity: 'legendary',
    unlockLevel: 1,
    ap: 3,
    costSpec: '40 ±30%',
    baseOutputSpec: '0',
    effects: ['BOTH: +60% ±30%', 'LINE_ALL_R: +30%'],
    flavor: '把每个 idea 都申请成专利',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'EMP_FOUNDER_R',
    name: '创始人 · 科学家',
    type: 'emp',
    dept: 'R',
    tier: '创始人',
    rarity: 'epic',
    unlockLevel: 1,
    ap: 3,
    costSpec: '15 ±10%',
    baseOutputSpec: '66 ±10%',
    effects: ['FOUNDER_AI_RD'],
    flavor: '“我们的目标是星辰大海与硬核科技！”——科学家出身的创始人，用代码与专利砸出行业未来。',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'EMP_FOUNDER_S',
    name: '创始人 · 销售冠军',
    type: 'emp',
    dept: 'S',
    tier: '创始人',
    rarity: 'epic',
    unlockLevel: 1,
    ap: 3,
    costSpec: '15 ±10%',
    baseOutputSpec: '66 ±10%',
    effects: ['FOUNDER_SALES_HIGH'],
    flavor: '“把这个 PPT 吹上天，今晚就签单！”——销冠出身的创始人，拥有把空气卖出高价的超级话术。',
    inStarterDeck: false,
    inRecruitPool: false,
  },
  {
    id: 'EMP_FOUNDER_O',
    name: '创始人 · 大厂 CXO',
    type: 'emp',
    dept: 'O',
    tier: '创始人',
    rarity: 'epic',
    unlockLevel: 1,
    ap: 3,
    costSpec: '15 ±10%',
    baseOutputSpec: '66 ±10%',
    effects: ['FOUNDER_LEAN_MANAGEMENT'],
    flavor: '“先对齐一下底层逻辑，打通闭环！”——大厂高管出身的创始人，用降本增效和组织架构横扫商海。',
    inStarterDeck: false,
    inRecruitPool: false,
  },
]

// ============================================================================
// 抽卡概率 (drawWeight) - 默认按稀有度分配，可在卡片定义里通过 drawWeight 字段覆写
// ============================================================================
export const DEFAULT_DRAW_WEIGHTS = {
  common: 100,
  rare: 40,
  elite: 12,
  epic: 4,
  legendary: 1,
}

// Mutate templates 一次性补齐 drawWeight 字段，以及 burn/asset 字段
for (const card of CARD_TEMPLATES) {
  if (card.type === 'fun') {
    card.ap = 0
    card.actionOptions = card.actionOptions ?? FUNCTION_CARD_ACTIONS[card.id] ?? [
      { id: 'default_draw', label: '临场判断', description: '抽 2 张牌', effect: { type: 'drawSelect', draw: 2, keep: 2 } },
    ]
    card.effects = card.actionOptions.map((option) => `ACTION: ${option.label}`)
  }
  if (card.drawWeight == null) {
    card.drawWeight = DEFAULT_DRAW_WEIGHTS[card.rarity] ?? 10
  }
  const rarityInfo = RARITY_TABLE[card.rarity] || RARITY_TABLE.common
  const tierBurn = card.type === 'emp' ? (TIER_BURN_BONUS[card.tier] ?? 0) : 0
  card.baseBurn = card.baseBurn ?? (rarityInfo.baseBurn + tierBurn)
  card.extraBurn = card.extraBurn ?? rarityInfo.extraBurn
  card.assetValue = card.assetValue ?? rarityInfo.assetValue
}



// ============================================================================
// 关间「董事会会议」数据 (详见 BOARD_MEETING_DESIGN.md)
// ============================================================================

/**
 * 商业模式 (Balatro Joker 类全局 buff) - 40 张
 * hook 类型：onMonthStart / onSettle / onCharge
 * 数量按稀有度逐级递减: common 14 / rare 12 / elite 8 / epic 4 / legendary 2
 *
 * 名字风格：流行管理理论 + 行业黑话 + 大厂模式
 * flavor 字段：hover 时显示的吐槽（保持幽默感）
 */
export const BUSINESS_MODELS = [
  // ============================================================================
  // onMonthStart · 月初触发 (15 张)
  // ============================================================================

  // ---- Common (5) ----
  {
    id: 'BM_01',
    name: '全员 Owner',
    hook: 'onMonthStart',
    payload: { type: 'drawBonus', value: 1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '月初抽牌 +1',
    flavor: '人人都是 Owner，问题来了：谁来当员工？决策很民主，背锅很模糊。德鲁克说的「赋权」不是这个意思。',
  },
  {
    id: 'BM_02',
    name: 'OKR 对齐',
    hook: 'onMonthStart',
    payload: { type: 'apIfHandRich', threshold: 6, value: 1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '月初手牌 ≥6 张时 AP +1',
    flavor: 'Objective 是大家一起写的，Key Result 是老板拍脑袋定的，绩效是 HR 评的。',
  },
  {
    id: 'BM_05',
    name: '差异化定位',
    hook: 'onMonthStart',
    payload: { type: 'handLimitBonus', value: 2 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '月初手牌上限 +2',
    flavor: '波特说要做差异化战略。客户问"你们和别家有什么不同？" 销售答："我们的 PPT 更精美。"',
  },
  {
    id: 'BM_14',
    name: 'PMO',
    hook: 'onMonthStart',
    payload: { type: 'drawBonus', value: 1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '月初抽牌 +1',
    flavor: '"项目管理办公室" = 5 个不写代码不做产品的人，每天追着所有人填表、对齐、复盘、风险评估。',
  },
  {
    id: 'BM_15',
    name: '抓大放小',
    hook: 'onMonthStart',
    payload: { type: 'handLimitBonus', value: 2 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '月初手牌上限 +2',
    flavor: '重要的事先做，次要的事"先放一放"。结果次要的事永远在"放一放"里，重要的事天天换。',
  },

  // ---- Rare (5) ----
  {
    id: 'BM_03',
    name: '降本增效',
    hook: 'onMonthStart',
    payload: { type: 'ccrBonus', value: 0.05 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '现金转化率 CCR +5%',
    flavor: '降的是别人的本，增的是 KPI 的效。寒冬必备技能，越降越冷。',
  },
  {
    id: 'BM_04',
    name: '精益创业',
    hook: 'onMonthStart',
    payload: { type: 'lineApDiscount', value: 1 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '每条产线 AP -1 (最低 1)',
    flavor: 'MVP 验证完没人用？那就 Pivot。Pivot 完还不行？继续 Pivot。Pivot 12 次后，融资到 B 轮。',
  },
  {
    "id": "BM_16",
    "name": "007",
    "hook": "onMonthStart",
    "payload": {
      "type": "apIfHandRich",
      "threshold": 6,
      "value": 1
    },
    "rarity": "rare",
    "unlockLevel": 4,
    "cost": 13,
    "description": "月初手牌 ≥6 张时 AP +1",
    "flavor": "我说的是大家都知道的知名大帅间谍，不是 24×7 在线，0 点睡 0 点起，0 假期这些。"
  },
  {
    id: 'BM_17',
    name: 'Sprint 冲刺',
    hook: 'onMonthStart',
    payload: { type: 'drawBonus', value: 2 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '月初抽牌 +2',
    flavor: 'Sprint 计划会 2 小时，回顾会 2 小时，写代码 2 小时。剩下时间打卡和填工时表。',
  },
  {
    id: 'BM_18',
    name: '数据驱动',
    hook: 'onMonthStart',
    payload: { type: 'ccrBonus', value: 0.10 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '现金转化率 CCR +10%',
    flavor: '决策不靠拍脑袋。改了 17 版 dashboard、跑了 23 次 AB 测试之后，还是靠老板拍脑袋。',
  },

  // ---- Elite (3) ----
  {
    id: 'BM_19',
    name: '中台建设',
    hook: 'onMonthStart',
    payload: { type: 'lineApDiscount', value: 2 },
    rarity: 'elite',
    unlockLevel: 4,
    cost: 18,
    description: '每条产线 AP -2 (最低 1)',
    flavor: '把所有部门的能力沉淀到中台。建完业务方不用，再建 2.0，还不用，建 3.0。终于有人用了——是中台自己的人在用。',
  },
  {
    id: 'BM_20',
    name: '起立坐下',
    hook: 'onMonthStart',
    payload: { type: 'drawBonus', value: 2 },
    rarity: 'elite',
    unlockLevel: 4,
    cost: 18,
    description: '月初抽牌 +2',
    flavor: '三个团队同做一个产品，每月汇报现场，老板说"你坐下，你起立，你来讲讲"。胜者通吃，败者解散。',
  },
  {
    id: 'BM_21',
    name: '砍价式管理',
    hook: 'onMonthStart',
    payload: { type: 'ccrBonus', value: 0.15 },
    rarity: 'elite',
    unlockLevel: 4,
    cost: 18,
    description: '现金转化率 CCR +15%',
    flavor: '没有中层，全是基层。"扁平化管理" = "所有人都直接汇报给老板" = "老板永远在开会"。',
  },

  // ---- Epic (1) ----
  {
    id: 'BM_22',
    name: '凡事 ROI',
    hook: 'onMonthStart',
    payload: { type: 'drawBonus', value: 3 },
    rarity: 'epic',
    unlockLevel: 6,
    cost: 24,
    description: '月初抽牌 +3',
    flavor: '会议要算 ROI，吃饭要算 ROI，上厕所要不要冲水也要算 ROI。HR 谈话之前先算 ROI。',
  },

  // ---- Legendary (1) ----
  {
    id: 'BM_23',
    name: '护城河信徒',
    hook: 'onMonthStart',
    payload: { type: 'handLimitBonus', value: 4 },
    rarity: 'legendary',
    unlockLevel: 7,
    cost: 30,
    description: '月初手牌上限 +4',
    flavor: '在别人贪婪时恐惧，在别人恐惧时贪婪，在他们都迷茫时，买消费品和手机大厂。然后等待 50 年。',
  },

  // ============================================================================
  // onSettle · 结算乘区 (15 张)
  // ============================================================================

  // ---- Common (5) ----
  {
    id: 'BM_06',
    name: '批量涌现',
    hook: 'onSettle',
    payload: { type: 'lineApDiscount', value: 1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '产线 AP -1',
    flavor: '明茨伯格说战略不是规划出来的，是涌现出来的。所以这一年到底干了什么？复盘的时候再编。',
  },
  {
    id: 'BM_08',
    name: '工程师文化',
    hook: 'onSettle',
    payload: { type: 'deptBonus', dept: 'R', value: 0.15 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: 'R 部门 +15%',
    flavor: '你有想法？写个 PRD。你有 PRD？写代码。你不会写代码？「那你来这里干嘛？」',
  },
  {
    id: 'BM_10',
    name: '北极星指标',
    hook: 'onSettle',
    payload: { type: 'p1Bonus', value: 0.1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: 'P1 启动位 +10%',
    flavor: '全公司只看一个核心指标。然后这个指标拆成 20 个二级指标，二级拆成 80 个三级。每个团队抱着自己的星，互不相干。',
  },
  {
    id: 'BM_24',
    name: '销售文化',
    hook: 'onSettle',
    payload: { type: 'deptBonus', dept: 'S', value: 0.15 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: 'S 部门 +15%',
    flavor: '做销售不丢人。Top sales 年薪 200 万，技术大牛 80 万。「这就是市场。」',
  },
  {
    id: 'BM_25',
    name: '运营驱动',
    hook: 'onSettle',
    payload: { type: 'deptBonus', dept: 'O', value: 0.15 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: 'O 部门 +15%',
    flavor: '运营的天职是兜底。研发提需求，产品改需求，运营 24 小时盯线上。',
  },

  // ---- Rare (4) ----
  {
    "id": "BM_07",
    "name": "本地部署Deapseak",
    "hook": "onSettle",
    "payload": {
      "type": "srvApDiscount",
      "value": 1
    },
    "rarity": "rare",
    "unlockLevel": 1,
    "cost": 13,
    "description": "服务卡 AP -1",
    "flavor": "“给你一个最直接、不绕弯子的答案：”"
  },
  {
    id: 'BM_09',
    name: 'All-in 增长',
    hook: 'onSettle',
    payload: { type: 'deptBonus', dept: 'S', value: 0.25 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: 'S 部门 +25%',
    flavor: 'ALL IN AI。ALL IN 元宇宙。ALL IN 大模型。ALL IN 出海。明年再 ALL IN 一个新方向。',
  },
  {
    id: 'BM_26',
    name: '飞轮效应',
    hook: 'onSettle',
    payload: { type: 'lineApDiscount', value: 2 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '产线 AP -2',
    flavor: '某电商大佬说的飞轮，一开始转得慢，转起来谁都拦不住。可惜大部分公司还在推飞轮的第一圈。',
  },
  {
    id: 'BM_27',
    name: '产品经理至上',
    hook: 'onSettle',
    payload: { type: 'p1Bonus', value: 0.2 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: 'P1 启动位 +20%',
    flavor: '"某果厂教主说过..." "设计学教父说过..." "某顶级产品经理说过..."。然后产品上线被骂烂。',
  },

  // ---- Elite (4) ----
  {
    id: 'BM_28',
    name: '颠覆式创新 2.0',
    hook: 'onSettle',
    payload: { type: 'deptBonus', dept: 'R', value: 0.3 },
    rarity: 'elite',
    unlockLevel: 4,
    cost: 18,
    description: 'R 部门 +30%',
    flavor: '管理学教科书说要从低端市场开始颠覆。我们说要从老板感兴趣的市场开始。',
  },
  {
    "id": "BM_29",
    "name": "现金牛牛矩阵",
    "hook": "onSettle",
    "payload": {
      "type": "ccrBonus",
      "value": 0.1
    },
    "rarity": "elite",
    "unlockLevel": 4,
    "cost": 18,
    "description": "现金转化率 +10%",
    "flavor": "没钱用BCG，用个他们的矩阵平替下～"
  },
  {
    id: 'BM_30',
    name: '政委巡查',
    hook: 'onSettle',
    payload: { type: 'deptBonus', dept: 'S', value: 0.3 },
    rarity: 'elite',
    unlockLevel: 4,
    cost: 18,
    description: 'S 部门 +30%',
    flavor: '组里有个"政委"，不写代码不做产品，但每周找你"谈话"两小时。谈完你就明白了。',
  },
  {
    id: 'BM_31',
    name: '永远微笑制',
    hook: 'onSettle',
    payload: { type: 'deptBonus', dept: 'O', value: 0.3 },
    rarity: 'elite',
    unlockLevel: 4,
    cost: 18,
    description: 'O 部门 +30%',
    flavor: '客户不是上帝，客户是体验。体验差了，就是你的问题。哪怕客户骂的是产品，那也是你的问题。',
  },

  // ---- Epic (1) ----
  {
    id: 'BM_32',
    name: '20% 副业制',
    hook: 'onSettle',
    payload: { type: 'deptBonus', dept: 'R', value: 0.4 },
    rarity: 'epic',
    unlockLevel: 6,
    cost: 24,
    description: 'R 部门 +40%',
    flavor: '每周可以花 20% 时间做自己想做的项目，剩下 80% 时间想该做什么。20% 项目里大部分变成了独立产品，少部分变成了"已关闭"。',
  },

  // ---- Legendary (1) ----
  {
    id: 'BM_33',
    name: '持有到老',
    hook: 'onSettle',
    payload: { type: 'p1Bonus', value: 0.3 },
    rarity: 'legendary',
    unlockLevel: 7,
    cost: 30,
    description: 'P1 启动位 +30%',
    flavor: '我们的持有期是永远，除非这家公司倒了，或者我活够了 100 岁。先到先得。',
  },

  // ============================================================================
  // onCharge · 一次性充能 (10 张)
  // ============================================================================

  // ---- Common (4) ----
  {
    id: 'BM_12',
    name: 'ESG 报告',
    hook: 'onCharge',
    payload: { type: 'levelEndBudgetBonus', value: 0.1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '关末战略预算 +10%',
    flavor: '把每个动作都包装成 Environmental, Social, Governance。投资人爱看 ESG，员工只能加班写报告。',
  },
  {
    id: 'BM_34',
    name: '券商进场',
    hook: 'onCharge',
    payload: { type: 'levelEndBudgetBonus', value: 0.15 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '关末战略预算 +15%',
    flavor: '讲故事比写代码重要。讲一个让承销商半夜睡不着、第二天连夜递招股书的故事。',
  },
  {
    id: 'BM_35',
    name: 'PR 公关战',
    hook: 'onCharge',
    payload: { type: 'levelEndBudgetBonus', value: 0.1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '关末战略预算 +10%',
    flavor: '今天上头条，明天上调查，后天上和解协议，下周继续上头条。流量就是价值。',
  },
  {
    id: 'BM_36',
    name: '使命愿景价值观',
    hook: 'onCharge',
    payload: { type: 'levelEndBudgetBonus', value: 0.1 },
    rarity: 'common',
    unlockLevel: 1,
    cost: 7,
    description: '关末战略预算 +10%',
    flavor: '墙上贴着「让世界更美好」，工位贴着「客户第一」，会议室贴着「拥抱变化」。然后开会讨论的还是怎么裁员省钱。柯林斯听了直摇头。',
  },

  // ---- Rare (3) ----
  {
    id: 'BM_13',
    name: '反脆弱',
    hook: 'onCharge',
    payload: { type: 'waiveMaintenance' },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '每关 1 次免维持费',
    flavor: '《黑天鹅》作者讲的反脆弱：不光要抗风险，要从风险中获益。我们目前只学会了抗。',
  },
  {
    id: 'BM_37',
    name: 'All Hands 大会',
    hook: 'onCharge',
    payload: { type: 'waiveMaintenance' },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '每关 1 次免维持费',
    flavor: 'All Hands Q&A 是企业文化的核心。除非问到敏感问题，那叫「下个问题」。',
  },
  {
    id: 'BM_38',
    name: '延链补链强链',
    hook: 'onCharge',
    payload: { type: 'levelEndBudgetBonus', value: 0.25 },
    rarity: 'rare',
    unlockLevel: 4,
    cost: 13,
    description: '关末战略预算 +25%',
    flavor: '上游延，下游补，中游强。延到了原材料，补到了渠道，强完发现：链上所有的钱都是自己花的。波特的价值链是这么用的？',
  },

  // ---- Elite (1) ----
  {
    id: 'BM_39',
    name: 'PPT 战略顾问',
    hook: 'onCharge',
    payload: { type: 'levelEndBudgetBonus', value: 0.3 },
    rarity: 'elite',
    unlockLevel: 4,
    cost: 18,
    description: '关末战略预算 +30%',
    flavor: '他们告诉你应该做什么，做完了再告诉你为什么没做好，最后告诉你下一步应该怎么做。账单 800 万，PPT 300 页。',
  },

  // ---- Epic (2) ----
  {
    id: 'BM_11',
    name: '颠覆式创新',
    hook: 'onCharge',
    payload: { type: 'reuseLine' },
    rarity: 'epic',
    unlockLevel: 6,
    cost: 24,
    description: '每关 1 次免冷却复用产线',
    flavor: '管理学教科书 1997 年提出，30 年来每个 CEO 都说自己在颠覆。真正颠覆的，10 个里有 1 个。',
  },
  {
    id: 'BM_40',
    name: '四宫格战略',
    hook: 'onCharge',
    payload: { type: 'reuseLine' },
    rarity: 'epic',
    unlockLevel: 6,
    cost: 24,
    description: '每关 1 次免冷却复用产线',
    flavor: '明星、奶牛、问号、瘦狗——把所有业务分成四类，然后什么也不做。咨询界的祖传 PPT。',
  },
]

/**
 * 卡包定义 (6 类，poolType 配合 engine.js 解析为具体卡池)
 */
export const PACK_DEFINITIONS = [
  {
    id: 'PACK_HEADHUNTER',
    name: '猎头礼包',
    icon: '👤',
    cost: 9,
    pickN: 1,
    fromN: 3,
    poolType: 'employee_common',
    description: '3 张普通员工卡选 1',
  },
  {
    id: 'PACK_ELITE',
    name: '精英礼包',
    icon: '⭐',
    cost: 24,
    pickN: 1,
    fromN: 3,
    poolType: 'employee_elite',
    description: '3 张精英员工卡选 1',
  },
  {
    id: 'PACK_SERVICE',
    name: '服务礼包',
    icon: '🛠️',
    cost: 12,
    pickN: 1,
    fromN: 3,
    poolType: 'service',
    description: '3 张服务卡选 1',
  },
  {
    id: 'PACK_FUNCTION',
    name: '功能礼包',
    icon: '📦',
    cost: 12,
    pickN: 1,
    fromN: 3,
    poolType: 'function',
    description: '3 张功能卡选 1',
  },
  {
    id: 'PACK_INSIGHT',
    name: '商业洞察',
    icon: '💡',
    cost: 18,
    pickN: 1,
    fromN: 3,
    poolType: 'business_model',
    description: '3 张商业模式选 1',
  },
  {
    id: 'PACK_MYSTERY',
    name: '神秘礼包',
    icon: '🎁',
    cost: 28,
    pickN: 1,
    fromN: 3,
    poolType: 'mystery',
    description: '跨稀有度，小概率出传奇',
  },
]

/**
 * HR 升职路径：只提升 tier，不改变 rarity
 */
export const UPGRADE_PATHS = {
  专员: { next: '经理', cost: 10 },
  经理: { next: '总监', cost: 15 },
  总监: { next: 'VP', cost: 20 },
  VP: { next: 'CXO', cost: 30 },
  CXO: null,
  创始人: null,
  顶级: null,
}

/**
 * 升职 ② 词缀附加池
 */
export const AFFIX_POOL = [
  { id: 'AFF_RIGHT_10', label: '→ 右邻 +10%', effects: ['RIGHT: +10%'] },
  { id: 'AFF_LEFT_10', label: '← 左邻 +10%', effects: ['LEFT: +10%'] },
  { id: 'AFF_BOTH_5', label: '↔ 双向 +5%', effects: ['BOTH: +5%'] },
  { id: 'AFF_SELF_8', label: '⚡ 自身 +8%', effects: ['SELF: +8%'] },
  { id: 'AFF_P5_20', label: '🎯 P5 +20%', effects: ['SELF_IF_P5: +20%'] },
  { id: 'AFF_COST_DOWN', label: '¥ 维持费 -1', effects: ['MAINT: -1'] },
]

/**
 * 董事访谈随机事件 (5 个首版原型)
 */
export const BOARD_EVENTS = [
  {
    id: 'EV_BM_01',
    title: '核心员工被挖',
    flavor: '某竞品猎头以高出 50% 的薪资来挖你最强的研发主管。HR 把决策权交给了董事会：',
    options: [
      { id: 'A', label: '留人 (−¥8)', cost: 8, effect: { type: 'noop' }, result: '✓ 留住了王牌研发，士气稳定' },
      { id: 'B', label: '放走', effect: { type: 'removeBudgetBonus', value: 4 }, result: '失去一员大将，但收到 4 ¥ 补偿' },
      { id: 'C', label: '反挖对方 (−¥12)', cost: 12, effect: { type: 'recruitLegendary', dept: 'R', count: 1 }, result: '🔥 反挖成功！下关获得 1 张 R 部门传奇候选' },
    ],
  },
  {
    id: 'EV_BM_02',
    title: '投资人施压',
    flavor: '投资人在董事会上拍桌子要求下一季度立刻见效，扬言不达标就换 CEO：',
    options: [
      { id: 'A', label: '妥协 (下关目标 +10%)', effect: { type: 'increaseNextTarget', value: 0.1 }, result: '✓ 投资人满意离场' },
      { id: 'B', label: '顶住 (−¥5)', cost: 5, effect: { type: 'noop' }, result: '强硬态度让你保住了战略自主权' },
      { id: 'C', label: '反手画饼 (+¥3，下关首月手牌 -1)', effect: { type: 'budgetGainNextMonthPenalty', budget: 3 }, result: '✓ 用愿景换到 3 ¥，但代价是下关首月手牌 -1' },
    ],
  },
  {
    id: 'EV_BM_03',
    title: '行业大会',
    flavor: '一年一度的行业大会即将召开，派哪个部门去最划算？',
    options: [
      { id: 'A', label: '派 R 团队', effect: { type: 'unlockEpic', dept: 'R' }, result: '✓ R 部门人脉打开，下关招聘池新增 1 张 R epic' },
      { id: 'B', label: '派 S 团队', effect: { type: 'unlockEpic', dept: 'S' }, result: '✓ S 部门拓展客户，下关招聘池新增 1 张 S epic' },
      { id: 'C', label: '派 O 团队', effect: { type: 'unlockEpic', dept: 'O' }, result: '✓ O 部门优化流程，下关招聘池新增 1 张 O epic' },
    ],
  },
  {
    id: 'EV_BM_04',
    title: '黑天鹅',
    flavor: '行业突发利好/利空各 50% 概率，赌不赌？',
    options: [
      { id: 'A', label: '顺势抄底', effect: { type: 'gamble', win: 10, lose: -5 }, result: '已写入顶栏' },
      { id: 'B', label: '谨慎观望', effect: { type: 'noop' }, result: '✓ 选择按兵不动' },
    ],
  },
  {
    id: 'EV_BM_05',
    title: '行业并购',
    flavor: '一家小型公司寻求被并购，吞下它能扩大商业模式上限：',
    options: [
      { id: 'A', label: '吞并 (−¥15，永久 +1 商业模式槽位)', cost: 15, effect: { type: 'increaseBmSlot' }, result: '✓ 并购完成，商业模式上限 +1' },
      { id: 'B', label: '拒绝 (+¥3)', effect: { type: 'budgetGain', value: 3 }, result: '保持精简，获得 3 ¥ 顾问费' },
      { id: 'C', label: '观望', effect: { type: 'noop' }, result: '✓ 没有动作' },
    ],
  },
]

export const STARTER_HAND = [
  ['EMP_R_01', 1],
  ['EMP_S_01', 1],
]

export const STARTER_DECK = [
  ['EMP_R_01', 2],
  ['EMP_S_01', 2],
  ['EMP_O_01', 2],
  ['EMP_R_02', 1],
  ['EMP_S_02', 1],
  ['EMP_O_02', 2],
  ['FUN_02', 1],
  ['FUN_03', 1],
  ['FUN_04', 1],
  ['FUN_01', 1],
  ['SRV_02', 1],
]

export function getCardTemplate(id) {
  const template = CARD_TEMPLATES.find((card) => card.id === id)
  if (!template) {
    throw new Error(`Unknown card template: ${id}`)
  }
  return template
}

export function expandDeck(list) {
  return list.flatMap(([id, count]) => Array.from({ length: count }, () => id))
}

export function findStageByValuation(v) {
  let current = STAGES[0]
  for (const s of STAGES) {
    if (v >= s.threshold) {
      current = s
    }
  }
  return current
}

export function getCardBurn(card) {
  return card.baseBurn ?? RARITY_TABLE[card.rarity]?.baseBurn ?? 0
}

export function getCardExtraBurn(card) {
  return card.extraBurn ?? RARITY_TABLE[card.rarity]?.extraBurn ?? 0
}

export function getBMMonthlyCost(bm) {
  return bm.monthlyCost ?? RARITY_TABLE[bm.rarity]?.bmMonthlyCost ?? 0
}

export function getCardAssetValue(card) {
  return card.assetValue ?? RARITY_TABLE[card.rarity]?.assetValue ?? 0
}

export function getBMAssetValue(bm) {
  return bm.assetValue ?? RARITY_TABLE[bm.rarity]?.bmAssetValue ?? 0
}

for (const bm of BUSINESS_MODELS) {
  const rarityInfo = RARITY_TABLE[bm.rarity] || RARITY_TABLE.common
  bm.monthlyCost = bm.monthlyCost ?? rarityInfo.bmMonthlyCost
  bm.assetValue = bm.assetValue ?? rarityInfo.bmAssetValue
}
