export const PERSON_MODULE_LIBRARY = {
  skin: {
    peach: { color: '#e9b887', shadow: '#b87954', blush: '#f6c2a0' },
    warm: { color: '#c9875a', shadow: '#8a5038', blush: '#e7a06f' },
    tan: { color: '#b87545', shadow: '#753d2b', blush: '#d8895e' },
    olive: { color: '#d0a46f', shadow: '#8d6540', blush: '#e8b987' },
    rose: { color: '#efb2a3', shadow: '#ad6a64', blush: '#ffc3bd' },
  },
  hairTone: {
    ink: '#1f2433',
    coffee: '#4b2c20',
    auburn: '#7c2d12',
    silver: '#c9d3df',
    violet: '#5b3aa4',
    teal: '#0f766e',
    gold: '#d9a441',
  },
  face: {
    round: { className: 'face-round' },
    square: { className: 'face-square' },
    sharp: { className: 'face-sharp' },
    soft: { className: 'face-soft' },
  },
  hair: {
    neat: { className: 'hair-neat' },
    messy: { className: 'hair-messy' },
    bob: { className: 'hair-bob' },
    wave: { className: 'hair-wave' },
    spike: { className: 'hair-spike' },
    bun: { className: 'hair-bun' },
    crown: { className: 'hair-crown' },
  },
  outfit: {
    hoodie: { className: 'outfit-hoodie', color: '#2563eb', shadow: '#1e3a8a' },
    lab: { className: 'outfit-lab', color: '#e5f0ff', shadow: '#93a8c6' },
    blazer: { className: 'outfit-blazer', color: '#1d4ed8', shadow: '#172554' },
    suit: { className: 'outfit-suit', color: '#334155', shadow: '#0f172a' },
    sales: { className: 'outfit-sales', color: '#dc2626', shadow: '#7f1d1d' },
    leather: { className: 'outfit-leather', color: '#7c2d12', shadow: '#431407' },
    opsVest: { className: 'outfit-ops-vest', color: '#16a34a', shadow: '#14532d' },
    finance: { className: 'outfit-finance', color: '#0f766e', shadow: '#134e4a' },
    executive: { className: 'outfit-executive', color: '#6d28d9', shadow: '#3b0764' },
    legendary: { className: 'outfit-legendary', color: '#f59e0b', shadow: '#92400e' },
  },
  neckwear: {
    none: { className: 'neck-none', color: 'transparent' },
    tie: { className: 'neck-tie', color: '#facc15' },
    bow: { className: 'neck-bow', color: '#fb7185' },
    scarf: { className: 'neck-scarf', color: '#38bdf8' },
    badge: { className: 'neck-badge', color: '#fef3c7' },
    medal: { className: 'neck-medal', color: '#fde047' },
  },
  eyewear: {
    none: { className: 'eye-none' },
    round: { className: 'eye-round' },
    square: { className: 'eye-square' },
    visor: { className: 'eye-visor' },
    shades: { className: 'eye-shades' },
  },
  accessory: {
    laptop: { className: 'acc-laptop', glyph: '</>' },
    flask: { className: 'acc-flask', glyph: 'AI' },
    wrench: { className: 'acc-wrench', glyph: '⌁' },
    phone: { className: 'acc-phone', glyph: '☎' },
    contract: { className: 'acc-contract', glyph: '¥' },
    megaphone: { className: 'acc-megaphone', glyph: '!' },
    headset: { className: 'acc-headset', glyph: 'CS' },
    chart: { className: 'acc-chart', glyph: '▥' },
    clipboard: { className: 'acc-clipboard', glyph: '✓' },
    calculator: { className: 'acc-calculator', glyph: '%' },
    trophy: { className: 'acc-trophy', glyph: '★' },
    crown: { className: 'acc-crown', glyph: '◆' },
    rocket: { className: 'acc-rocket', glyph: '↑' },
    network: { className: 'acc-network', glyph: '◎' },
    book: { className: 'acc-book', glyph: '§' },
    bot: { className: 'acc-bot', glyph: 'fn' },
  },
  background: {
    rdLab: { className: 'bg-rd-lab', a: '#1d4ed8', b: '#0f172a', mark: '{}' },
    salesStage: { className: 'bg-sales-stage', a: '#dc2626', b: '#3f1111', mark: '¥' },
    opsBoard: { className: 'bg-ops-board', a: '#16a34a', b: '#113a22', mark: '✓' },
    boardroom: { className: 'bg-boardroom', a: '#7c3aed', b: '#27114d', mark: 'IPO' },
    serviceDesk: { className: 'bg-service-desk', a: '#b45309', b: '#3b2508', mark: 'SVC' },
    functionPanel: { className: 'bg-function-panel', a: '#475569', b: '#111827', mark: 'MOD' },
  },
  effect: {
    none: { className: 'fx-none' },
    code: { className: 'fx-code' },
    money: { className: 'fx-money' },
    ops: { className: 'fx-ops' },
    stars: { className: 'fx-stars' },
    aura: { className: 'fx-aura' },
    legendary: { className: 'fx-legendary' },
  },
}
