export const PERSON_MODULE_TABLE = {
  EMP_R_01: { hair: 'messy', outfit: 'hoodie', eyewear: 'none', accessory: 'laptop', neckwear: 'none', background: 'rdLab' },
  EMP_R_02: { hair: 'neat', outfit: 'blazer', eyewear: 'square', accessory: 'laptop', neckwear: 'tie', background: 'rdLab' },
  EMP_R_03: { hair: 'wave', outfit: 'suit', eyewear: 'square', accessory: 'wrench', neckwear: 'badge', background: 'rdLab' },
  EMP_R_04: { hair: 'bob', outfit: 'lab', eyewear: 'round', accessory: 'flask', neckwear: 'scarf', background: 'rdLab', effect: 'code' },
  EMP_R_05: { hair: 'messy', outfit: 'hoodie', eyewear: 'visor', accessory: 'laptop', neckwear: 'none', background: 'rdLab', effect: 'code' },
  EMP_R_06: { hair: 'neat', outfit: 'suit', eyewear: 'square', accessory: 'wrench', neckwear: 'tie', background: 'rdLab' },
  EMP_R_07: { hair: 'wave', outfit: 'executive', eyewear: 'square', accessory: 'rocket', neckwear: 'medal', background: 'boardroom', effect: 'aura' },
  EMP_R_08: { hair: 'crown', outfit: 'lab', eyewear: 'round', accessory: 'flask', neckwear: 'medal', background: 'rdLab', effect: 'stars' },
  EMP_R_09: { hair: 'spike', outfit: 'hoodie', eyewear: 'visor', accessory: 'laptop', neckwear: 'badge', background: 'rdLab', effect: 'code' },
  EMP_R_10: { hair: 'spike', outfit: 'leather', eyewear: 'visor', accessory: 'laptop', neckwear: 'none', background: 'rdLab', effect: 'code' },
  EMP_R_11: { hair: 'neat', outfit: 'suit', eyewear: 'round', accessory: 'book', neckwear: 'tie', background: 'boardroom' },
  EMP_R_12: { hair: 'wave', outfit: 'executive', eyewear: 'visor', accessory: 'rocket', neckwear: 'medal', background: 'boardroom', effect: 'aura' },
  EMP_R_13: { hair: 'bob', outfit: 'lab', eyewear: 'visor', accessory: 'flask', neckwear: 'scarf', background: 'rdLab', effect: 'stars' },
  EMP_R_14: { hair: 'messy', outfit: 'hoodie', eyewear: 'round', accessory: 'network', neckwear: 'badge', background: 'rdLab', effect: 'code' },
  EMP_R_15: { hair: 'spike', outfit: 'hoodie', eyewear: 'visor', accessory: 'rocket', neckwear: 'none', background: 'rdLab', effect: 'stars' },
  LEG_R_01: { hair: 'crown', outfit: 'legendary', eyewear: 'round', accessory: 'trophy', neckwear: 'medal', background: 'boardroom', effect: 'legendary' },
  LEG_R_02: { hair: 'crown', outfit: 'legendary', eyewear: 'visor', accessory: 'trophy', neckwear: 'medal', background: 'rdLab', effect: 'legendary' },

  EMP_S_01: { hair: 'neat', outfit: 'sales', eyewear: 'none', accessory: 'phone', neckwear: 'badge', background: 'salesStage' },
  EMP_S_02: { hair: 'wave', outfit: 'sales', eyewear: 'square', accessory: 'phone', neckwear: 'tie', background: 'salesStage' },
  EMP_S_03: { hair: 'neat', outfit: 'suit', eyewear: 'shades', accessory: 'contract', neckwear: 'medal', background: 'salesStage', effect: 'money' },
  EMP_S_04: { hair: 'wave', outfit: 'sales', eyewear: 'shades', accessory: 'contract', neckwear: 'tie', background: 'salesStage', effect: 'money' },
  EMP_S_05: { hair: 'messy', outfit: 'leather', eyewear: 'none', accessory: 'megaphone', neckwear: 'scarf', background: 'salesStage' },
  EMP_S_06: { hair: 'bob', outfit: 'sales', eyewear: 'round', accessory: 'chart', neckwear: 'badge', background: 'salesStage' },
  EMP_S_07: { hair: 'wave', outfit: 'executive', eyewear: 'shades', accessory: 'trophy', neckwear: 'medal', background: 'boardroom', effect: 'aura' },
  EMP_S_08: { hair: 'crown', outfit: 'legendary', eyewear: 'shades', accessory: 'trophy', neckwear: 'medal', background: 'salesStage', effect: 'legendary' },
  EMP_S_09: { hair: 'neat', outfit: 'sales', eyewear: 'round', accessory: 'headset', neckwear: 'badge', background: 'salesStage' },
  EMP_S_10: { hair: 'wave', outfit: 'sales', eyewear: 'none', accessory: 'megaphone', neckwear: 'scarf', background: 'salesStage', effect: 'money' },
  EMP_S_11: { hair: 'neat', outfit: 'suit', eyewear: 'shades', accessory: 'contract', neckwear: 'medal', background: 'boardroom', effect: 'money' },
  EMP_S_12: { hair: 'crown', outfit: 'executive', eyewear: 'shades', accessory: 'megaphone', neckwear: 'medal', background: 'boardroom', effect: 'aura' },
  EMP_S_13: { hair: 'wave', outfit: 'leather', eyewear: 'shades', accessory: 'network', neckwear: 'scarf', background: 'salesStage', effect: 'stars' },
  EMP_S_14: { hair: 'neat', outfit: 'legendary', eyewear: 'shades', accessory: 'trophy', neckwear: 'medal', background: 'salesStage', effect: 'money' },
  EMP_S_15: { hair: 'bob', outfit: 'executive', eyewear: 'round', accessory: 'headset', neckwear: 'medal', background: 'boardroom', effect: 'aura' },
  LEG_S_01: { hair: 'crown', outfit: 'legendary', eyewear: 'shades', accessory: 'trophy', neckwear: 'medal', background: 'salesStage', effect: 'legendary' },
  LEG_S_02: { hair: 'wave', outfit: 'legendary', eyewear: 'none', accessory: 'rocket', neckwear: 'medal', background: 'boardroom', effect: 'legendary' },

  EMP_O_01: { hair: 'bob', outfit: 'opsVest', eyewear: 'round', accessory: 'clipboard', neckwear: 'badge', background: 'opsBoard' },
  EMP_O_02: { hair: 'neat', outfit: 'opsVest', eyewear: 'square', accessory: 'clipboard', neckwear: 'tie', background: 'opsBoard' },
  EMP_O_03: { hair: 'wave', outfit: 'suit', eyewear: 'square', accessory: 'chart', neckwear: 'medal', background: 'opsBoard', effect: 'ops' },
  EMP_O_04: { hair: 'bob', outfit: 'opsVest', eyewear: 'round', accessory: 'clipboard', neckwear: 'scarf', background: 'opsBoard' },
  EMP_O_05: { hair: 'neat', outfit: 'finance', eyewear: 'square', accessory: 'calculator', neckwear: 'tie', background: 'opsBoard' },
  EMP_O_06: { hair: 'messy', outfit: 'opsVest', eyewear: 'round', accessory: 'chart', neckwear: 'badge', background: 'opsBoard', effect: 'ops' },
  EMP_O_07: { hair: 'wave', outfit: 'executive', eyewear: 'square', accessory: 'crown', neckwear: 'medal', background: 'boardroom', effect: 'aura' },
  EMP_O_08: { hair: 'bun', outfit: 'opsVest', eyewear: 'round', accessory: 'clipboard', neckwear: 'medal', background: 'opsBoard', effect: 'ops' },
  EMP_O_09: { hair: 'bob', outfit: 'finance', eyewear: 'visor', accessory: 'chart', neckwear: 'badge', background: 'opsBoard', effect: 'code' },
  EMP_O_10: { hair: 'neat', outfit: 'opsVest', eyewear: 'square', accessory: 'wrench', neckwear: 'tie', background: 'opsBoard', effect: 'ops' },
  EMP_O_11: { hair: 'bob', outfit: 'lab', eyewear: 'visor', accessory: 'chart', neckwear: 'scarf', background: 'opsBoard', effect: 'code' },
  EMP_O_12: { hair: 'wave', outfit: 'executive', eyewear: 'square', accessory: 'crown', neckwear: 'medal', background: 'boardroom', effect: 'aura' },
  EMP_O_13: { hair: 'bun', outfit: 'legendary', eyewear: 'round', accessory: 'wrench', neckwear: 'medal', background: 'opsBoard', effect: 'stars' },
  EMP_O_14: { hair: 'neat', outfit: 'suit', eyewear: 'round', accessory: 'clipboard', neckwear: 'tie', background: 'opsBoard', effect: 'ops' },
  EMP_O_15: { hair: 'wave', outfit: 'finance', eyewear: 'square', accessory: 'calculator', neckwear: 'medal', background: 'boardroom', effect: 'money' },
  LEG_O_01: { hair: 'crown', outfit: 'legendary', eyewear: 'round', accessory: 'crown', neckwear: 'medal', background: 'opsBoard', effect: 'legendary' },
  LEG_O_02: { hair: 'crown', outfit: 'legendary', eyewear: 'round', accessory: 'book', neckwear: 'medal', background: 'boardroom', effect: 'legendary' },
  LEG_M_01: { hair: 'crown', outfit: 'legendary', eyewear: 'shades', accessory: 'rocket', neckwear: 'medal', background: 'boardroom', effect: 'legendary' },
}
